gazebosim/gz-physics

Changelog.md, dartsim/src/JointFeatures.cc, dartsim/src/JointFeatures_TEST.cc, dartsim/worlds/ground.sdf
The issue occurs if a model is spawned and is attached to a parent model without a call to `step()` in between. This should be fixed in DART, but in the meantime, we can just call `incrementVersion` after `moveTo` is called on a DART BodyNode.
=> Fix collision issue with detachable joints

tpe/lib/src/Model.cc, tpe/lib/src/Model.hh, tpe/lib/src/Shape.cc, tpe/lib/src/Shape_TEST.cc
`tpelib::BoxShape::GetSize()` was declared but not implemented in previous PR and caused windows CI failure in `tpe_plugin` PR
`tpelib::Model::GetCanonicalLink()` assumes the first link of each model is the canonical link, thus enabling ign-gazebo to find the link entity https://github.com/ignitionrobotics/ign-gazebo/blob/2259f027cd3a244f2c841b62c968088eace1b338/src/systems/physics/Physics.cc#L1233 and update world pose accordingly. 
This PR needs to be merged before #32
=> Add tpelib::Shape::GetSize() and tpelib::Model::GetCanonicalLink()

Changelog.md, dartsim/src/Base.hh, dartsim/src/EntityManagementFeatures.cc, dartsim/src/JointFeatures.cc, dartsim/src/JointFeatures_TEST.cc, dartsim/worlds/joint_across_models.sdf
The is was originally opened by @scpeters before the Github migration ([archived PR](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/pull-requests/104)). I have modified it to store the original names of links and using those names when moving BodyNodes between skeletons.
=> Restore detached BodyNodes to original skeleton

CMakeLists.txt, Changelog.md, dartsim/src/Base.hh, dartsim/src/Collisions_TEST.cc, dartsim/src/EntityManagementFeatures.cc, dartsim/src/JointFeatures.cc, dartsim/src/JointFeatures_TEST.cc, dartsim/src/ShapeFeatures.cc, dartsim/src/ShapeFeatures.hh, dartsim/worlds/ground.sdf, dartsim/worlds/joint_across_models.sdf, include/ignition/physics/PlaneShape.hh, include/ignition/physics/detail/PlaneShape.hh
* Merge from `ign-physics1`
* Update changelog
* Bump version
=> Bump to 2.1 ⬆️

tools/code_check.sh, tpe/lib/src/Collision.cc, tpe/lib/src/Collision.hh, tpe/lib/src/Engine.cc, tpe/lib/src/Engine.hh, tpe/lib/src/Link.cc, tpe/lib/src/Link.hh, tpe/lib/src/Model.cc, tpe/lib/src/Model.hh, tpe/lib/src/Model_TEST.cc, tpe/lib/src/Shape.cc, tpe/lib/src/Shape.hh, tpe/lib/src/World.cc, tpe/lib/src/World.hh, tpe/plugin/src/Base.hh, tpe/plugin/src/Base_TEST.cc, tpe/plugin/src/EntityManagementFeatures.cc, tpe/plugin/src/EntityManagement_TEST.cc, tpe/plugin/src/FreeGroupFeatures.cc, tpe/plugin/src/KinematicsFeatures.hh, tpe/plugin/src/SDFFeatures.cc, tpe/plugin/src/SDFFeatures_TEST.cc, tpe/plugin/src/ShapeFeatures.cc, tpe/plugin/src/SimulationFeatures.cc, tpe/plugin/src/SimulationFeatures_TEST.cc
Add tpe to codecheck and fix errors. Remove white spaces and shorten line length. Closes #58
Uses `sh tools/code_check.sh` to conduct code check on tpe
=> Fix TPE codecheck errors

tpe/lib/src/Collision.cc, tpe/lib/src/Collision.hh, tpe/lib/src/Entity.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Model_TEST.cc, tpe/lib/src/Shape.hh, tpe/lib/src/Utils.cc, tpe/lib/src/Utils.hh, tpe/lib/src/Utils_TEST.cc
Add helper function that returns an entity's bounding box by recursively merging it's children's bounding boxes.
=> [Citadel] [TPE] Add function to get an Entity's bounding box

tpe/lib/src/Collision.cc, tpe/lib/src/Entity.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Link.cc, tpe/lib/src/Model.cc, tpe/lib/src/Model_TEST.cc
Added flags to keep track of entity changes so that we can return cached data like collide bitmasks and bounding box if no changes are detected.
While making these changes, I noticed there was already a flag to keep track of bounding box changes (`bboxDirty`) but it was never set to true so bounding boxes were never recomputed.
I added some logic and public functions to to help propagate these flags up the tree (`Set|GetParent`, `ChildrenChanged`). Not ideal so feedback welcome. 
Signed-off-by: Ian Chen <ichen@osrfoundation.org>
=> [Citadel][TPE] Cache Entity data

Changelog.md, dartsim/CMakeLists.txt, dartsim/src/JointFeatures.cc, dartsim/src/SDFFeatures_TEST.cc
This enforces joint limits by using the Joint::FORCE actuator and calling `Joint::setCommand` instead of `Joint::setForce`. https://github.com/ignitionrobotics/ign-physics/commit/f9ff53adc07695644260169ec50f02f339b1ca68 fixes a joint effort limit test by making sure a joint force is set after `World::step` is called because DART clears joint forces after `World::step`. This makes the test fail in that commit. The commit also uses the ignition-physics Feature to set joint forces so that the whole API is tested. https://github.com/ignitionrobotics/ign-physics/commit/c2685feccc8fcb9443761337ed53a07f0db9a194 fixes the failing test.
Closes https://github.com/ignitionrobotics/ign-gazebo/issues/226
=> Enforce joint effort limit in dartsim-plugin

tpe/lib/src/Collision.cc, tpe/lib/src/Collision.hh, tpe/lib/src/CollisionDetector.cc, tpe/lib/src/Collision_TEST.cc, tpe/lib/src/Entity.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Link.cc, tpe/lib/src/Model.cc, tpe/lib/src/Model_TEST.cc, tpe/plugin/src/EntityManagementFeatures.cc, tpe/plugin/src/EntityManagementFeatures.hh, tpe/plugin/src/SDFFeatures.cc, tpe/plugin/src/SDFFeatures.hh, tpe/plugin/src/SimulationFeatures_TEST.cc, tpe/plugin/worlds/shapes_bitmask.sdf
Added collide bitmask to Collisions in tpelib for doing collision filtering. 
Since collision detection in TPE is done between models (not collisions), I also added a function to Entity to get a single combined (bitwise OR'd) collide bitmask from all child collisions. e.g. if one collision within model A can collide with any one of the collisions in model B then the two models should collide. 
Also added the CollisionFilterMaskFeature similar to the way it was done for dart in this [pull reqeuest](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/pull-requests/116/page/1)
=> [Citadel][TPE] Implement collision filtering using collide bitmasks and add CollisionFilterMaskFeature

Changelog.md, include/ignition/physics/SpecifyData.hh, include/ignition/physics/detail/PrivateSpecifyData.hh, include/ignition/physics/detail/SpecifyData.hh, src/CompositeData.cc, src/SpecifyData_TEST.cc
This fixes a crash when copying `SpecifyData` objects and implements a copy constructor for `ExpectData` so that copied objects don't share the same underlying iterator to `DataMap`. 
This was causing unexpected test failures in #40.
- https://github.com/ignitionrobotics/ign-physics/commit/3b480dda6e21b63cf33fa52b8aeef2c231c5aa1b adds a test that segfaults because a `SpecifyData` is copied. 
- https://github.com/ignitionrobotics/ign-physics/commit/51cfb62388e959b9d7926e753c2cf21f9f3262cb fixes the segfault, but the test fails because the copied objects share an iterator.
- https://github.com/ignitionrobotics/ign-physics/commit/aa2c61de4f9be9e8374e500724719689606a2614 Fixes the test by implementing a copy constructor and copy assignment operator for `ExpectData`. Note that implementing …
=> Fix copying SpecifyData objects

tpe/lib/src/Entity.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Link_TEST.cc
Use `pose` instead of `tf` to keep track of relative transformation. Add `GetWorldPose` to get entity pose relative to world, `GetPose` to get entity pose relative to parent. This change will make tpe more consistent with the rest of the library.
Signed-off-by: Ian Chen <ichen@osrfoundation.org>
=> testing world pose function

.github/workflows/ci-bionic.yml, CMakeLists.txt, bitbucket-pipelines.yml
Several CI PRs will need to be merged before this goes in.
=> Bump to SDFormat 10 for Dome

codecov.yml, tools/code_check.sh, tpe/lib/CMakeLists.txt, tpe/lib/src/AABBTree.cc, tpe/lib/src/AABBTree.hh, tpe/lib/src/AABBTree_TEST.cc, tpe/lib/src/CollisionDetector.cc, tpe/lib/src/CollisionDetector.hh, tpe/lib/src/CollisionDetector_TEST.cc, tpe/lib/src/Entity.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Model.cc, tpe/lib/src/World.cc, tpe/lib/src/aabb_tree/AABB.cc, tpe/lib/src/aabb_tree/AABB.h, tpe/lib/src/aabb_tree/LICENSE
Initial performance tests revealed a bottleneck in TPE's naive collision detection algorithm. This PR integrates an AABB tree from a third party library to help with collision detection by checking for overlaps between objects' axis aligned bounding boxes.
I tested 3 AABB tree libraries and [the one](https://github.com/lohedges/aabbcc) chosen has the best performance while providing more features like tree balancing.
Here're graphs comparing the `World::Step` performance in ign-gazebo's [shapes_population.sdf](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo3/examples/worlds/shapes_population.sdf) world that consists of 3000 models.
TPE before (~779ms) :
TPE after using AABB tree (~17ms)
Dart (~155ms):
The performance of TPE with AABB tree is roughly 45x faster than before …
=> Integrate AABB tree for collision checking in TPE

tutorials/01_intro.md, tutorials/02_installation.md, tutorials/03_physics_plugins.md
Signed-off-by: John Shepherd <john@openrobotics.org>
=> Tutorial tweaks

tutorials/02_installation.md
Code snippets indented by 4 spaces were being treated as preformatted text. Just removing the indent puts the code snippet at the wrong indentation level. The solution is to remove the extra line between a bullet point and the code snippet.
=> Fix code snippet rendering

.github/workflows/ci.yml
@claireyywang , this is needed for CI to run for forks.
=> Enable actions CI for forks

CMakeLists.txt
The `CONFIG` argument to `find_package` does not have a [corresponding argument in `ign_find_package`](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.5.0/cmake/IgnUtils.cmake#L3-L15), though it happens to work in our `ign_find_package(DART)` call by accident since it gets treated as a component. It can be properly passed through as an `EXTRA_ARGS` parameter.
To reproduce the bug, change the order of the `ign_find_package` parameters with the following patch and observe that it gives a cmake warning for unrecognized arguments:
~~~
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a732852..1c384ac 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -61,11 +61,11 @@ ign_find_package(sdformat10 REQUIRED_BY sdf dartsim tpe)
#-------------------------------------- …
=> Fix CONFIG arg in ign_find_package(DART) call

CMakeLists.txt
Backport #119 to ign-physics2. Use rebase and merge.
Original description:
Fix CONFIG arg in ign_find_package(DART) call (#119)
The CONFIG argument to find_package does not have a corresponding
argument in ign_find_package, though it happens to work in our
ign_find_package(DART) call by accident since it gets treated
as a component. It can be properly passed through as an
EXTRA_ARGS parameter.
Signed-off-by: Steve Peters <scpeters@openrobotics.org>
=> Backport #119 to ign-physics2: Fix CONFIG arg in ign_find_package(DART) call

tpe/plugin/src/KinematicsFeatures.cc, tpe/plugin/src/SimulationFeatures_TEST.cc
By default the `GetAxisAlignedBoundingBox` feature requests a model's bounding box in world frame, and computes it by merging all child links and shapes' bounding boxes in the requested frame. The problem was that we did not have support for getting frame data for shapes in the KinematicsFeatures so the bounding box returned was incorrect. The PR adds an extra check in the collision (shape) list when searching for frame data.
Signed-off-by: Ian Chen <ichen@osrfoundation.org>
=> Fix getting model bounding box in world frame in TPE

dartsim/src/JointFeatures.cc, dartsim/src/JointFeatures_TEST.cc
Robots falling through the floor were reported in https://github.com/osrf/subt/issues/675. This was caused by an input joint velocity command of `nan`  being passed to `JointFeatures::SetJointVelocityCommand` via ign-gazebo's DiffDrive system. In DART, Joint velocity commands are handled by the constraint solver, which also handles collisions, so it makes sense that the robot falls through when the solver fails. The solution here is to ignore `nan` values in `JointFeatures::SetJointVelocityCommand`.
I have taken the opportunity to ignore invalid values in other `JointFeatures::SetJoint*` commands as well.
=> Ignore invalid joint commands

bullet/src/plugin.cc
This was added in the initial PR to have a dummy feature to be able of compiling the plugin. However, is not expected to be there for the basic tests we are targetting.
=> [Bullet] Remove dummy engine feature

tutorials.md.in, tutorials/07-implementing-a-physics-plugin.md
Signed-off-by: anindex <an.thai.le97@gmail.com>
=> Tutorial implement a physics plugin

bullet/src/Base.hh, bullet/src/FreeGroupFeatures.cc, bullet/src/FreeGroupFeatures.hh, bullet/src/SDFFeatures.cc, bullet/src/plugin.cc
FreeGroupFeatures properly detected by ignition.
Convert from eigen to bullet functions were moved to base so any file can reuse them instead of having to declare them again
=> [Bullet] FreeGroupFeatures + convert functions

bullet/src/SimulationFeatures.cc, bullet/src/SimulationFeatures.hh, bullet/src/plugin.cc
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
Connects to #44
=> [Bullet] Add ForwardStep feature

tutorials.md.in, tutorials/08-implementing-a-custom-feature.md
Signed-off-by: anindex <an.thai.le97@gmail.com>
=> Tutorial implement a custom feature

dartsim/CMakeLists.txt, test/plugins/CMakeLists.txt, tools/check_test_ran.py, tpe/plugin/CMakeLists.txt
These are some fixes needed to compile against dartsim on Windows, as mentioned in #87. Though dartsim version 6.9.4 is [now available in vcpkg](https://github.com/microsoft/vcpkg/blob/master/ports/dartsim/portfile.cmake), this version is missing some needed fixes (https://github.com/dartsim/dart/pull/1510, https://github.com/dartsim/dart/pull/1513), so I recommend building dart's `master` branch from source in a colcon workspace alongside this branch. Unfortunately, dart still seems to have some runtime errors (https://github.com/dartsim/dart/issues/1522), so all the tests that use the `dartsim-plugin` currently fail, but at least the build succeeds.
The fixes include:
* creating the unversioned plugin by copy instead of symlink, following the example of TPE
* setting some compiler flags …
=> dartsim-plugin windows build fixes

bullet/src/KinematicsFeatures.cc, bullet/src/KinematicsFeatures.hh, bullet/src/plugin.cc
Signed-off-by: Lobotuerk <jtlorente@ekumenlabs.com>
=> Kinematics features

include/ignition/physics/CylinderShape.hh, include/ignition/physics/FreeGroup.hh, include/ignition/physics/Joint.hh, include/ignition/physics/RemoveEntities.hh, include/ignition/physics/Shape.hh
=> API documentation common Set* features

bullet/src/Base.hh, bullet/src/EntityManagementFeatures.cc, bullet/src/SDFFeatures.cc, bullet/src/SDFFeatures.hh, bullet/src/SimulationFeatures.hh
Collision seems to be working, deleting and creating does not segfault, bodies seem to move properly
=> [Bullet] Collision Features

include/ignition/physics/ConstructEmpty.hh
Signed-off-by: anindex <an.thai.le97@gmail.com>
From issue #9
=> API documentation common Construct* features

bullet/src/SDFFeatures.cc, bullet/src/SDFFeatures.hh
This is to create links in a way similar to dartsim. I think this probably may avoid issues with duplicated links. As bullet doesn't save the names of the links, the names are searched in the `links` unordered map.
=> [bullet] Add find or construct link

bullet/src/SDFFeatures.cc, bullet/src/ShapeFeatures.cc, bullet/src/ShapeFeatures.hh, bullet/src/plugin.cc
Mesh collision seems to be working, at least with the duck.dae model.
=> [Bullet] Mesh features

dartsim/src/EntityManagementFeatures.cc, tpe/lib/src/Entity.cc
Classic `=` vs `==` typo that wasn't caught at compile time because of the pimpl's raw pointer not enforcing const correctness.
It disabled the optimization that skipped updating the AABB tree for entities that didn't move, so the PR should help improve performance.
=> Fix TPE poseDirty getter

include/ignition/physics/Entity.hh
Resolves #176.
I don't know why GCC 10 isn't able to associate the `Policy` alias to `PolicyT` correctly. Maybe there's a more appropriate way of fixing this while still using `Policy`, I'm not sure.
I haven't tried the fix with GCC 8 or 9, nor clang. Let's see what CI says.
While at it, I also expanded `F` to `FeatureF` to keep the pattern and make it easier to find.
=> Fix compilation with GCC 10.2.0

dartsim/src/EntityManagementFeatures.cc, dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures_TEST.cc, dartsim/worlds/test.world
This PR adds the support of simulating bouncing using [`//collision/surface/bounce/restitution_coefficient`](http://sdformat.org/spec?ver=1.7&elem=collision#surface_bounce). It calls the methods introduced in https://github.com/dartsim/dart/pull/1369.
This is the resulting behaviour simulating 11 spheres with a different restitution coefficient and setting the coefficient of the ground to `1.0`:
<details>
<summary>Script (requires third party libraries)</summary>
```py
import numpy as np
from dataclasses import dataclass
from gym_ignition.utils import misc
from scenario import core as scenario_core
from scenario import gazebo as scenario_gazebo
from gym_ignition.utils.scenario import init_gazebo_sim
@dataclass
class SphereURDF:
mass: float = 5.0
radius: float = 0.1
restitution: float = 0 …
```
=> Add restitution coefficient support for bouncing

tpe/lib/src/CollisionDetector.cc, tpe/lib/src/CollisionDetector_TEST.cc, tpe/lib/src/Entity.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Model_TEST.cc, tpe/plugin/src/SDFFeatures.cc
This PR introduces skipping collision checking when going through the AABB tree for static objects.
This change allows large performance gains in worlds with a lot of static objects but very few non static ones.
Apart from some complex test scenarios we are working on (where I observed about 300% performance gain) I went for a pathological case and generated a [shapes_population](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/examples/worlds/shapes_population.sdf.erb) with a total of 1500 shapes (500 per type), all set to static except one and I had about double the performance (12% RTF before, 24% RTF after).
I'm considering adding caching to the CollisionDetector where, if an object didn't move since the previous time step, its collision detection step will be skipped. …
=> TPE: Skip computing collisions for static objects

.github/ci/packages.apt, CMakeLists.txt, bitbucket-pipelines.yml, dartsim/src/EntityManagementFeatures.cc, dartsim/src/JointFeatures_TEST.cc, dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures_TEST.cc, dartsim/worlds/test.world, tpe/plugin/worlds/test.world, tutorials/05_plugin_loading.md, tutorials/06-physics-simulation-concepts.md, tutorials/07-implementing-a-physics-plugin.md
Addresses https://github.com/ignition-tooling/release-tools/issues/360
=> Bump in edifice: sdformat11

README.md, tutorials/02_installation.md
- Retarget of #184 for Citadel via cherry-pick
- Add note about DART and TPE in d87feba40c9e7c738e4b560e9f3a7497f385d70b
- Standardize tutorial to be uniform with ign-common
Partially addresses ignitionrobotics/docs#117
=> Add Windows installation

dartsim/src/EntityManagementFeatures.cc
Signed-off-by: claireyywang <22240514+claireyywang@users.noreply.github.com>
=> fix cpplint error

bullet/src/JointFeatures.cc, bullet/src/SDFFeatures.cc
This PR:
* Adds revoluteJoints with world as parent
* Fixes segfault related to default axis
* Adds missing getters/setters for revoluteJoints
This PR was tested using `joint_controller.sdf` and `joint_position_controller.sdf`
=> [Bullet] Adds missing getters/setters revolute joints

bullet/src/SimulationFeatures.hh
Closes #<NUMBER>
Removed GetContactsFromLastStepFeature from the engine's features.
Compile and try running any simulation with bullet engine, depends on https://github.com/ignitionrobotics/ign-gazebo/pull/690
=> [Bullet] Removing GetContactsFromLastStepFeature from Simulation Features

dartsim/src/SimulationFeatures.cc, dartsim/src/SimulationFeatures.hh, dartsim/src/SimulationFeatures_TEST.cc, include/ignition/physics/ForwardStep.hh, tpe/plugin/src/SimulationFeatures.cc, tpe/plugin/src/SimulationFeatures.hh, tpe/plugin/src/SimulationFeatures_TEST.cc
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
Related to #223 
Possible solution for #219
#223 added functionality to DART and TPE to write changed link data from an iteration to `ForwardStep::Output` so that downstream libraries like `ign-gazebo` can use this data for more efficient post-physics processing/updates (https://github.com/ignitionrobotics/ign-gazebo/pull/678). In order for downstream libraries to make this functionality optional, the changed link data that is written to by DART and TPE must be of type `ExpectedData` instead of `RequiredData` (that way, downstream libraries can see if this data was actually written to or not). This PR makes this change.
Using this PR with https://github.com/ignitionrobotics/ign-gazebo/pull/678, users can run the [`ign-gazebo` physics …
=> Add "ChangedWorldPose" to ForwardStep::Output's expected data

Changelog.md
Preparation for 4.0.0~pre1 release.
Comparison to version 3: https://github.com/ignitionrobotics/ign-physics/compare/ign-physics3...main
The version in `CMakeLists` is already up-to-date.
We need to make sure the `dart-bullet` component is correctly set, see https://github.com/ignition-tooling/release-tools/pull/420
=> 🎈 4.0.0~pre1

examples/hello_world_loader/README.md, examples/hello_world_plugin/README.md
Update example Windows instructions
=> Improved Windows instructions

tpe/lib/src/Entity.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Link.cc, tpe/lib/src/Link.hh, tpe/lib/src/Link_TEST.cc, tpe/lib/src/Model.cc, tpe/lib/src/Model.hh, tpe/lib/src/Model_TEST.cc, tpe/lib/src/World.cc, tpe/plugin/src/FreeGroupFeatures.cc, tpe/plugin/src/SDFFeatures.cc
Support updating individual link pose, related to https://github.com/ignitionrobotics/ign-gazebo/pull/427
=> [TPE] Update link pose

.github/ci/packages.apt, CMakeLists.txt, bitbucket-pipelines.yml, tutorials/06-physics-simulation-concepts.md
See https://github.com/ignition-tooling/release-tools/issues/428
=> Bumps in fortress : ign-physics5

test/plugins/DARTDoublePendulum.cc
Fix for dart deprecation warning copied from #262.
Keep using the old method for dart 6.9 and earlier, but use the new method for 6.10+.
=> Fix dart deprecation warning

dartsim/src/SDFFeatures.cc, dartsim/src/ShapeFeatures.cc, dartsim/src/ShapeFeatures_TEST.cc
Fixes API incompatibility between upstream and our fork of dart
The `getSlipCompliance` and `setSlipCompliance` APIs were present in our fork of dartsim 6.10.0 but not in the recent upstream release. The `getPrimarySlipCompliance` and `setPrimarySlipCompliance` are used in the upstream release of dartsim 6.10.0 and were recently added for our fork of dart, so we should use them for compatibility. A replacement for #249
=> Use slip compliance API's available in upstream dartsim release

tpe/lib/src/AABBTree.cc, tpe/lib/src/Collision.hh, tpe/lib/src/CollisionDetector.cc, tpe/lib/src/Entity.hh, tpe/lib/src/Link.hh, tpe/lib/src/Model.hh, tpe/lib/src/Shape.cc, tpe/lib/src/Shape.hh
Removes unnecessary copy constructors and insures that all destructors are marked `virtual` where appropriate.
=> Clean up functions that trigger GCC9 warnings

CMakeLists.txt, Changelog.md, Migration.md
Preparation for 4.2.0~pre1 release.
Comparison to 4.1.0: https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics4_4.1.0...ign-physics4
Pull requests that could be included: #275, https://github.com/ignitionrobotics/ign-physics/pull/231 
=> 🎈 4.2.0~pre1 Prerelease

dartsim/src/KinematicsFeatures.cc, dartsim/src/LinkFeatures_TEST.cc, dartsim/src/ShapeFeatures_TEST.cc, dartsim/src/WorldFeatures.cc, dartsim/src/WorldFeatures.hh, dartsim/src/WorldFeatures_TEST.cc, include/ignition/physics/World.hh, include/ignition/physics/detail/FrameSemantics.hh, include/ignition/physics/detail/World.hh
This adds a feature for getting and setting the gravity vector in a `World`. This was motivated by a failing test in #261.
The [LinkFeatures_TEST](https://github.com/ignitionrobotics/ign-physics/blob/ignition-physics4_4.1.0/dartsim/src/LinkFeatures_TEST.cc#L84-L91) currently loads an `sdf::World` object then copies it in order to modify the `<gravity/>` SDFormat element, with a comment noting "// TODO Add a world property feature to set gravity instead of this hack". In `ignition-physics3` and earlier, this was a useful hack, but it doesn't work in `ignition-physics4` due to an internal change in `libsdformat11`. I've illustrated the problem by adding some failing test expectations in e270f65 that call `sdf::World::ValidateGraphs`. Loading the `sdf::World` from an `sdf::ElementPtr` does …
=> Add Gravity Feature, fix LinkFeatures_TEST

dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures_TEST.cc, dartsim/worlds/test.world
https://github.com/ignitionrobotics/sdformat/pull/622 will remove `sdf::JointAxis::InitialPosition`, so we need to stop using it here.
=> Remove use of deprecated function sdf::JointAxis::InitialPosition

src/CMakeLists.txt
Avoid to use `EIGEN3_INCLUDE_DIRS` variable with `target_include_directories` command, as this result in hardcoding the `EIGEN3_INCLUDE_DIRS` value in the ignition-physics build machine, that could be different from the location where the Eigen3 include directories are installed in the machine that is consuming the ignition-physics CMake package. 
=> Make ignition-physics CMake config files relocatable

tpe/plugin/src/KinematicsFeatures.cc, tpe/plugin/src/SimulationFeatures.cc, tpe/plugin/src/SimulationFeatures.hh, tpe/plugin/src/SimulationFeatures_TEST.cc
This PR fixes two separate issues regarding TPE:
The first one was likely introduced in the performance optimization PRs (such as #223). Velocity control of models using TPE now doesn't work anymore. To try it out compare the results of:
`ign gazebo /home/luca/ws_edifice/src/ign-gazebo/examples/worlds/velocity_control.sdf --physics-engine ignition-physics-tpe-plugin`
and
`ign gazebo /home/luca/ws_edifice/src/ign-gazebo/examples/worlds/velocity_control.sdf `
The green vehicle does not move under TPE.
My suspicion is that it is due to the fact that instead of sending all the links we now send only updated links and since the velocity is updated at the model level the links themselves are not updated.
The fix I came up with involves iterating over the models in the update step (skipping …
=> Fix TPE Link velocity not being updated and Model velocity not having any effect.

include/ignition/physics/ign_auto_headers.hh.in
Removes an unused file
The [ign_auto_headers.hh.in](https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/ign_auto_headers.hh.in) is provided by ign-cmake, but for some reason, this package has an old, unused copy in the source code. We can just remove it. Many other `ign-` packages have this as well, so it can be removed from there when convenient.
=> Remove unused ign_auto_headers.hh.in

CMakeLists.txt, Changelog.md
Preparation for 2.5.0 release.
Comparison to 2.5.0-pre1: https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics2_2.5.0-pre1...ign-physics2
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/847, https://github.com/ignitionrobotics/ign-gazebo/pull/869
~- [ ] Updated migration guide (as needed)~
=> Prepare for 2.5.0 release

CMakeLists.txt, sdf/CMakeLists.txt
Needed by https://github.com/ignitionrobotics/sdformat/pull/780
This links to the proper cmake target for `sdformat`, which is better than using the `SDFormat_LIBRARIES` variable. That variable may be removed in https://github.com/ignitionrobotics/sdformat/pull/780, so it's good to make this change now.
=> Link to sdformat10 cmake target

dartsim/include/ignition/physics/dartsim/World.hh, dartsim/src/CustomFeatures.cc, dartsim/src/CustomFeatures.hh, tutorials/05_plugin_loading.md, tutorials/06-physics-simulation-concepts.md, tutorials/07-implementing-a-physics-plugin.md, tutorials/08-implementing-a-custom-feature.md
Targeting `main` because that's the version of the tutorial rendered on ignitionrobotics.org.
- For some reason, doxygen `\include` doesn’t work with `CMakeLists.txt`. I think it doesn’t like the .txt extension, for if I copy its content to `CMakeLists.cc`, then `\include` is able to render it. So I copied the file content for now and added a TODO.
- 3 snippets from `dartsim/` are not showing in tutorial 08 for some reason. I added tags in the code, double-checked against other places that work, and still couldn’t get them to show up. It’s bizarre.
Compile the tutorials
```
colcon build --packages-select ignition-physics6 --merge-install
```
- Fix for `05_plugin_loading.md` "Loading physics plugins"
Navigate to the current tutorial and check CMakeLists.txt snippet is missing: …
=> Fix tutorials broken ref links, snippets, image widths

tutorials/05_plugin_loading.md, tutorials/07-implementing-a-physics-plugin.md, tutorials/08-implementing-a-custom-feature.md
Followup of https://github.com/ignitionrobotics/ign-physics/pull/312
Depends on https://github.com/ignitionrobotics/ign-cmake/pull/198
With https://github.com/ignitionrobotics/ign-cmake/pull/198 , now the snippets in tutorials 5, 7, 8 show up correctly.
Recompile
```
colcon build --packages-select ignition-physics6 ignition-cmake2 --merge-install
```
(Is it okay for this PR to target `ign-physics` `main` and that one to `ign-cmake2`? The tutorials are only fixed on `main` and not Garden. Can backport to `ign-physics5` if needed.)
Navigate to those 3 tutorials from the local page, and check that the snippets to `CMakeLists.txt`, `dartsim/*/.cc`, and `dartsim/*/.hh` are showing:
```
file:///path/to/ign/build/ignition-physics6/doxygen/html/tutorials.html
```
**Note to maintainers**: Remember …
=> Fix tutorial snippets with new Doxygen filters

examples/hello_world_loader/CMakeLists.txt, examples/hello_world_plugin/CMakeLists.txt, examples/simple_plugin/CMakeLists.txt
This should fix CMake warnings that are turning the Jenkins build yellow since we migrated to Focal in https://github.com/ignition-tooling/release-tools/pull/565
=> Add project() to examples

dartsim/include/ignition/physics/dartsim/World.hh, dartsim/src/CustomFeatures.cc, dartsim/src/CustomFeatures.hh, tutorials/05_plugin_loading.md, tutorials/06-physics-simulation-concepts.md, tutorials/07-implementing-a-physics-plugin.md, tutorials/08-implementing-a-custom-feature.md
Backport #312 and #316 to Citadel
~~After this manual backport to Citadel, will it eventually be forward-ported with everything else to Edifice and Fortress, so we don't have to do those backports manually?~~ (Confirmed in #316)
Fix ref links not linking, code snippets being blank boxes, image widths too wide, etc.
See the problems in tutorials 5, 6, 7, and 8 before this PR:
https://ignitionrobotics.org/api/physics/2.5/tutorials.html
Make sure you `git pull` ign-cmake so you have ignitionrobotics/ign-cmake#198
Recompile
```
colcon build --packages-select ignition-physics2 ignition-cmake2 --merge-install
```
Check the problems are fixed in the local Doxygen generated page:
```
file:///path/to/ign/build/ignition-physics2/doxygen/html/tutorials.html
```
**Note to maintainers**: Remember to …
=> Backport #312 and #316 to Citadel

dartsim/src/JointFeatures_TEST.cc, dartsim/src/KinematicsFeatures_TEST.cc, dartsim/src/LinkFeatures_TEST.cc, dartsim/src/ShapeFeatures_TEST.cc, dartsim/src/WorldFeatures_TEST.cc
Backport #325 to edifice. Use rebase and merge.
=> Fix Apache license version (backport to edifice)

tpe/lib/src/Shape.cc, tpe/lib/src/Shape.hh
Cleans up warnings eg:
```
/home/mjcarroll/workspaces/ign_garden/src/ign-physics/tpe/lib/src/Shape.cc: In copy constructor ‘ignition::physics::tpelib::CapsuleShape::CapsuleShape(const ignition::physics::tpelib::CapsuleShape&)’:
/home/mjcarroll/workspaces/ign_garden/src/ign-physics/tpe/lib/src/Shape.cc:98:11: warning: implicitly-declared ‘ignition::physics::tpelib::CapsuleShape& ignition::physics::tpelib::CapsuleShape::operator=(const ignition::physics::tpelib::CapsuleShape&)’ is deprecated [-Wdeprecated-copy]
98 |   *this = _other;
|           ^~~~~~
```
Signed-off-by: Michael Carroll <michael@openrobotics.org>.
=> Remove explicitly-defined copy constructor/operator

.github/ci/packages-jammy.apt, .github/workflows/ci.yml
Part of https://github.com/ignition-tooling/release-tools/issues/566
Enable CI for Ubuntu 22.04 (Jammy)
=> Add Ubuntu Jammy CI

.github/ci/packages-bionic.apt, .github/workflows/ci.yml, README.md, tutorials/02_installation.md
* See https://github.com/ignition-tooling/release-tools/issues/597
`ign-physics6` will be on Garden.
No Bionic builds should be triggered.
=> Remove Bionic from future releases (Garden+)

include/ignition/physics/SpecifyData.hh, include/ignition/physics/detail/SpecifyData.hh
=> Fix ExpectData compiler warnings

CMakeLists.txt
Signed-off-by: Ashton Larkin <42042756+adlarkin@users.noreply.github.com>
Requires https://github.com/ignitionrobotics/ign-cmake/pull/211
This PR makes use of https://github.com/ignitionrobotics/ign-cmake/pull/211 to revert the changes made in https://github.com/ignitionrobotics/ign-physics/pull/121. Once this is merged, it will need to be forward-ported to `ign-physics5`.
=> Make CONFIG a CMake pass-through option for DART

bullet/src/SDFFeatures.cc
Added collision shapes to Capsule and Ellipsoid
I didn't add test because it's a little bit messy. we need to refactor tests
=> Bullet: Added collision shape to Capsule and Ellipsoid

CMakeLists.txt, bullet/CMakeLists.txt, dartsim/CMakeLists.txt, heightmap/CMakeLists.txt, include/gz/physics/CMakeLists.txt, mesh/CMakeLists.txt, sdf/CMakeLists.txt, src/CMakeLists.txt, test/benchmark/CMakeLists.txt, test/integration/CMakeLists.txt, test/performance/CMakeLists.txt, test/regression/CMakeLists.txt, test/static_assert/CMakeLists.txt, tpe/lib/CMakeLists.txt, tpe/plugin/CMakeLists.txt
* Part of https://github.com/gazebo-tooling/release-tools/issues/719
=> [ign -> gz] CMake functions

test/common_test/CMakeLists.txt, test/common_test/basic_test.cc
Use command line arguments to setup the physic engine library.
FYI @scpeters 
=> Suggestion: Added basic architecture for common tests with cmd arguments

dartsim/src/Base.hh, dartsim/src/JointFeatures.cc
* Remove welded dummy bodies and the associated `WeldJointConstraint` when detaching a joint.
* Fixes integer divisions.
=> Suggestions to #352

dartsim/src/Base.hh, dartsim/src/JointFeatures.cc, dartsim/src/JointFeatures_TEST.cc, dartsim/src/SDFFeatures.cc, dartsim/worlds/joint_constraint.sdf
Alternative to #345 and #347 
With inspiration from #345 and #347, this implements a variation on the approach from gazebo-classic for handling non-tree kinematics (including kinematic loops) with the reduced coordinate Featherstone formulation by splitting links and welding them back together with a constraint. This adds data to the `LinkInfo` struct and a `SplitAndWeldLink` helper function to `Base.hh`. The test made by @arjo129 is included as well.
This only implements support for kinematic loops in the `AttachFixedJoint` method, but it should be applicable in other `Attach*Joint` methods and the `ConstructSdfJoint` method to support non-tree kinematics in more cases.
This implementation differs slightly from the approach in gazebo-classic. In gazebo11, all joints that are created …
=> dartsim: support non-tree kinematics in AttachFixedJoint

Migration.md, dartsim/src/SDFFeatures.cc, dartsim/worlds/falling.world, tutorials/04-switching-physics-engines.md
See: https://github.com/gazebo-tooling/release-tools/issues/744
=> ign -> gz Shared Lib Migration : gz-physics

CMakeLists.txt, bullet/CMakeLists.txt
Remove warning, Use `GzBullet` instead of `IgnBullet`.
=> Use GzBullet instead of IgnBullet

bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/WorldFeatures.cc, bullet-featherstone/src/WorldFeatures.hh, bullet-featherstone/src/plugin.cc, test/common_test/CMakeLists.txt, test/common_test/world_features.cc, test/common_test/worlds/test.world
Added gravity to bullet-featherstone. Also fixed a bug when loading the world related to sdf bullet tags
=> Added gravity feature to bullet-featherstone

src/CMakeLists.txt
Restore `CXX_STANDARD` export in core library that was removed in #1059 and also tests https://github.com/gazebosim/gz-cmake/pull/273
Similar to https://github.com/gazebosim/sdformat/pull/1072, this is mainly testing https://github.com/gazebosim/gz-cmake/pull/273 using the `ci_matching_branch/` trickery with https://github.com/osrf/homebrew-simulation/commit/406b74a7e7c19591d62437fb1d57d1dadd012e3d and https://github.com/gazebo-tooling/gazebodistro/commit/b4274333b8b0810cd72368c2372895bd1acd9b2a, but it does make a small improvement of its own, restoring the `CXX_STANDARD` export.
=> Restore CXX_STANDARD export from core library

Changelog.md, dartsim/src/CustomHeightmapShape.cc, dartsim/src/SimulationFeatures.cc, dartsim/src/SimulationFeatures.hh
See: https://github.com/gazebo-tooling/release-tools/issues/767
=> ign -> gz Provisional Finale: Source Migration : gz-physics

bullet/src/Base.hh, bullet/src/EntityManagementFeatures.cc, bullet/src/EntityManagementFeatures.hh, bullet/src/SDFFeatures.cc
This PR fixes the entity management features for the bullet classic plugin. It also fixes the seg fault that was reported [in this other PR](https://github.com/gazebosim/gz-sim/pull/1560) for gz-sim.
=> Fix bullet classic entity management

README.md
Fixes whitespace in README
Fixes some whitespace in README and adds mention of deprecated headers in include/ignition
=> README: fix whitespace

include/gz/physics/ForwardStep.hh, include/gz/physics/FrameID.hh, include/gz/physics/FrameSemantics.hh, include/gz/physics/detail/FrameSemantics.hh
These small tweaks to the ABI are needed for #373, and if we can merge these before code freeze then we can introduce `bullet-featherstone` post-release without and harmful effects.
=> ABI tweaks to help bullet-featherstone

dartsim/src/SDFFeatures.cc
Fixes a bug in moment of inertia calculation
When loading a model from SDF in the dartsim plugin, the moment of inertia matrix is currently applying any rotations in the `//inertial/pose` two times, since the rotations are applied explicitly in SDFFeatures.cc, but they are already applied in [math::Inertial::Moi](https://github.com/gazebosim/gz-math/blob/ign-math6/include/ignition/math/Inertial.hh#L131-L132).
I confirmed the bug with a slightly modified version of the [inertia_rotations](https://github.com/osrf/gazebo/blob/gazebo11/test/worlds/inertia_rotations.world) test world from gazebo classic. That world has multiple 1x4x9 boxes with identical inertia values that are expressed with different inertial pose rotations. The boxes are initially standing up on a ground plane. Setting …
=> dartsim: fix handling inertia matrix pose rotation

coverage.ignore.in, dartsim/src/SDFFeatures.cc
Port `ign-physics5 ` ➡️  `main`
Branch comparision: https://github.com/ignitionrobotics/ign-physics/compare/main...ign-physics5
=> Merge ign-physics5 ➡️  main

dartsim/src/JointFeatures_TEST.cc, dartsim/src/KinematicsFeatures_TEST.cc, dartsim/src/LinkFeatures_TEST.cc, dartsim/src/ShapeFeatures_TEST.cc, src/FeatureList_TEST.cc, test/integration/DoublePendulum.cc, test/integration/FeatureSystem.cc, tpe/lib/src/CollisionDetector_TEST.cc, tpe/lib/src/Collision_TEST.cc, tpe/plugin/src/ShapeFeatures.cc
Part of: https://github.com/gazebo-tooling/release-tools/issues/784
=> ign -> gz : Remove redundant namespace references

bullet-featherstone/src/SDFFeatures.cc
- Improved joint constraint (limit, damping, friction, ...)
- Fixed crash when a joint type is not supported or a link has several parent joints
Launch gz-sim with `gz-sim/test/worlds/demo_joint_types.sdf`
=> Improved joints in bullet featherstone

tutorials/02_installation.md
Signed-off-by: Joan Aguilar Mayans <joan@openrobotics.org>
Part of Garden tutorial party, issue https://github.com/gazebosim/garden-tutorial-party/issues/295. Updates to source installation instructions for Ubuntu (Focal).
- Added instructions to install packages `gnupg`, `wget`, and `cppcheck`.
- Updated references to packages/branches.
Note that since this is pointing to a pre-release, I had to use `ubuntu-nightly` rather than `ubuntu-stable` for the instructions to work. I'm assuming that this will resolve itself once the prerelease becomes a proper release.
=> Updates to installation documentation

tutorials/03_physics_plugins.md
Signed-off-by: Joan Aguilar Mayans <joan@openrobotics.org>
Fixes https://github.com/gazebosim/garden-tutorial-party/issues/333 through https://github.com/gazebosim/garden-tutorial-party/issues/340.
Updated some links to point to the `gz-physics6` branch rather than the (nonexisting) `ign-physics6` branch.
=> Fix broken links in the physics plugin tutorial

tutorials/04-switching-physics-engines.md
Improved 04-switching-physics-engines instructions. Related to https://github.com/gazebosim/garden-tutorial-party/issues/330
=> Improved 04-switching-physics-engines instructions

bullet-featherstone/src/Base.hh, bullet-featherstone/src/SDFFeatures.cc
Meshes were not colliding with the static plane. This PR should fix this issue.
=> Fixed bullet-featherstone mesh collisions

bullet/CMakeLists.txt
Backport #436.
Fixes windows build by not unconditionally adding symbolic links.
=> Backport windows fix

bullet-featherstone/src/KinematicsFeatures.cc, bullet-featherstone/src/LinkFeatures.cc, bullet-featherstone/src/LinkFeatures.hh, bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/SimulationFeatures.cc, bullet-featherstone/src/plugin.cc, test/common_test/CMakeLists.txt, test/common_test/addexternalforcetorque.cc, test/common_test/joint_features.cc, test/common_test/worlds/joint_constraint.sdf, test/common_test/worlds/sphere.sdf
=> Bullet-featherstone: Apply external forces and torques

test/common_test/simulation_features.cc
Attempt to diagnose the ellipsoid failure on focal CI.
=> Bullet-featherstone: fix ellipsoid on focal

bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/SDFFeatures.hh, bullet/src/SDFFeatures.cc, bullet/src/SDFFeatures.hh, dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures.hh, sdf/include/gz/physics/sdf/ConstructCollision.hh, tpe/plugin/src/SDFFeatures.cc, tpe/plugin/src/SDFFeatures.hh
Removed `GetCollision`. FYI @scpeters and @mjcarroll 
=> Removed GetCollision API it's redundant

dartsim/src/SDFFeatures.cc
This makes dartsim correctly handle nested models.  The simulation runner may try to construct models twice (First from the root sdf::Model, and then again because the nested model is in the ECM).  This will return the originally constructed model rather than creating a duplicate.
=> Fix construction of nested models

include/gz/physics/FeatureList.hh
This triggers a warning in downstream libraries such as:
https://build.osrfoundation.org/job/ign_gazebo-pr-win/5195/msbuild/
```
'gz::physics::detail::ComposePlugin::type': base-class 'gz::physics::detail::ComposePlugin::n,void>' is already a base-class of 'gz::physics::detail::ComposePlugin::type'
```
 
After talking with @mxgrey, while this is typically a relevant warning by MSVC, it is not applicable so we can suppress it.
=> Suppress MSVC warning that is not applicable

test/common_test/construct_empty_world.cc
Deduplicate some code in common tests
This is a prototype of some deduplication of code in the common tests:
* https://github.com/gazebosim/gz-physics/commit/adf1147ee53d26318263eddca137bcf8123cd1cb: reference feature lists recursively to avoid repeating feature names
* https://github.com/gazebosim/gz-physics/commit/af8e428f19cf1a84b8fd5fa0bb752fb8e0071839: add templatized helper function for requesting engine and loading an empty world and replace duplicate code in all test cases. Some additional helper functions could be added to further reduce the code duplication.
=> Deduplicate common tests part1

dartsim/src/SDFFeatures.cc
Partially addresses #450 by reducing the verbosity of the two errors from "error" to "debug".
In reality, these aren't really errors per se, as the dartsim plugin continues to process the SDF and then attaches meshes and heightmaps in a later stage.
The recent addition of https://github.com/gazebosim/gz-sim/pull/1560 allowing SDF to be constructed in a single shot uncovered these unimplemented functions.
The more complete fix is to take advantage of constructing the models in place, which I have opening an issue for at #451.
=> Reduce error to debug and add notes

CMakeLists.txt
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Preparation for 2.6.0~pre1 release.
Comparison to 2.5.1: https://github.com/gazebosim/gz-physics/compare/ignition-physics2_2.5.1...ign-physics2
=> 2.6.0~pre1

CMakeLists.txt, Changelog.md
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Preparation for 2.6.0 release.
Comparison to 2.5.1: https://github.com/gazebosim/gz-physics/compare/ignition-physics2_2.5.1...ign-physics2
Needed by https://github.com/gazebosim/gz-sim/pull/1646
=> 2.6.0 release

dartsim/include/CMakeLists.txt, mesh/include/CMakeLists.txt, sdf/include/CMakeLists.txt
Fixes unstable debbuilds
The debbuilds from 2.6.0 are unstable due to some CMakeLists.txt files being accidentally installed.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-physics2-debbuilder&build=140)](https://build.osrfoundation.org/job/ign-physics2-debbuilder/140/) https://build.osrfoundation.org/job/ign-physics2-debbuilder/140/
This takes an approach similar to gazebosim/gz-common#449 to ensure that they aren't installed.
=> Don't install CMakeLists.txt files

bullet-featherstone/src/SimulationFeatures.hh, bullet/src/Base.hh, bullet/src/SimulationFeatures.cc, bullet/src/SimulationFeatures.hh
The existing pose computation used pose data that was never updated by the physics engine. This causes gz-sim to skip updating the poses of links. To test, run `gz sim -v 4 --physics-engine gz-physics-bullet-plugin rolling_shapes.sdf -r`. Without this PR, the shapes do not move.
=> [bullet]: Fix how changed link poses are computed

dartsim/src/Base.hh, dartsim/src/SimulationFeatures.cc
DART 6.13.0 was tagged yesterday and is already available on homebrew. This PR fixes a compilation errors related to `ContactSurfaceParams`, which was a feature added in our fork first and upstreamed. Variable names were changed during the upstreaming process, which now has to be resolved. 
This also fixes a compilation warning with using `BodyNode::getShapeNodes` which is now deprecated and as been replaced by `BodyNode::eachShapeNode`.
=> Fix build errors and warnings for DART 6.13.0

CMakeLists.txt, Changelog.md
Preparation for 2.6.1 release.
Comparison to 2.6.0: https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics2_2.6.0...ign-physics2
Needed to fix homebrew binaries
=> Prepare for 2.6.1 Release

bullet/src/Base.hh, bullet/src/SDFFeatures.cc, bullet/src/plugin.cc
=> Fix windows warnings related to bullet

CMakeLists.txt, Changelog.md
Preparation for 5.3.0 release.
Comparison to 5.2.0: https://github.com/gazebosim/gz-physics/compare/ignition-physics5_5.2.0...ign-physics5
Needed to fix homebrew binaries
=> Prepare for 5.3.0 Release

dartsim/src/SDFFeatures.cc
The memory corruption seems to occur only on DART 6.9.2 (version that comes with Ubuntu 20.04), but not 6.12 (Ubuntu 22.04), so I'm led to believe it's a bug in dart that has since been fixed. But the patch in this PR seems to avoid the problem by not storing the freejoint created when creating links. My suspicion is that this freejoint is not properly taken into account when removing skeletons.
This is blocking https://github.com/gazebosim/gz-sim/pull/1836 as the test `INTEGRATION_recreate_entities` is reliably failing on CI. Running the test under `valgrind` shows that a memory corruption occurs while trying to decrement a reference count of a skeleton. With this patch, the `valgrind` error goes away.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message …
=> Fix memory corruption due to faulty refcount tracking

dartsim/CMakeLists.txt, dartsim/src/Base.hh, dartsim/src/Base_TEST.cc
The joint index obtained from the skeleton counts the freejoint, which is not in line with joint indexing in gz-physics API where there is no notion of free joints. This fixes the `INTEGRATION_recreate_entities` test in gz-sim which broke due to a forward port of #480 to gz-physics6.
=> Fix joint index used in bookkeeping

dartsim/src/Base.hh
The entity addition logic is for each type of entity. This refactors it to an `AddEntity` member function. This will be used in a follow up PR for supporting world joints.
=> dartsim: Refactor entity addition logic in the EntityStorage class

bullet-featherstone/src/Base.hh, test/plugins/CMakeLists.txt
Fixes https://github.com/gazebosim/gz-physics/issues/497
This fixes two tests with segfaults on macOS
1. `COMMON_TEST_simulation_features_bullet-featherstone`: The failure appears to be due to the destruction order of the `triangleMeshes` and `meshesGImpact` containers.  Per [this] (https://github.com/bulletphysics/bullet3/issues/567#issuecomment-186248424) comment, memory in bullet is sensitive to order of destruction. `meshesGImpact` objects contain pointers to items contained by`triangleMeshes`, so the solution is to ensure `meshesGImpact` is destructed before `triangleMeshes`.
2. `INTEGRATION_DoublePendulum`: This is a DART test, but the segfault seems to be related to Bullet. I found that even after removing all the code in `DARTDoublePendulum.cc`, the segfault still occurs as long …
=> Fix bullet related segfaults on macOS

bullet-featherstone/src/SDFFeatures.cc, test/common_test/simulation_features.cc, test/common_test/worlds/multiple_collisions.sdf
Only the first collision element in a link was created when using bullet-featherstone. This PR adds each collision shape as a childShape to the bullet collider.
=> Support multiple collisions per link in bullet-featherstone

test/common_test/TestLibLoader.hh, test/common_test/joint_features.cc, test/common_test/simulation_features.cc
We've recently accidentally started testing the Bullet and Bullet-featherstone plugins on Windows because one of our Jenkins nodes had Bullet installed. This created a few failures that looked like regressions, but were never meant to be tested. Instead of removing Bullet from the Jenkins node, we've decided to disable the failing tests so it's more explicit and so it'd be less steps to take in case we wanted to fix them down the road.
Also in this PR, I noticed that some of the tests were loading worlds from all plugins simultaneously instead of loading each plugin and world one by one. ~Perhaps some of the test failures are caused by that~, but in any case, I think we want to load the plugins one at a time, so I've made changes accordingly.
**Note to maintainers**: Remember to use …
=> Disable failing bullet(-featherstone) tests on windows

test/common_test/simulation_features.cc
Fixes #440 
There were some uninitialized values that were used before #503 , so checking if we can re-enable AABB now that those are fixed.
=> Re-enable AABB tests for ellipsoids

dartsim/src/Base.hh, dartsim/src/EntityManagementFeatures.cc, dartsim/src/EntityManagementFeatures.hh, dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures.hh, include/gz/physics/GetEntities.hh, include/gz/physics/detail/GetEntities.hh, test/common_test/joint_features.cc, test/common_test/world_features.cc, test/common_test/worlds/world_joint_test.sdf
Closes https://github.com/gazebosim/gz-physics/issues/457
As of https://github.com/gazebosim/sdformat/pull/1117, SDFormat supports joints under world (`//world/joint` in xpath). But in gz-physics, Entities such as joints are only available in a Model. To support world joints, instead of creating a new type of entity, we have chosen to implement a scheme where the world behaves like a model via the `WorldModelFeature` feature. Given a world, `w`, we can do `model = w->GetWorldModel()` to get the model proxy. We can then use any of the APIs supported by the features available in the physics engine, e.g., `model->GetJoint("j1")` where "j1" is a joint directly under `<world>` in the SDFormat.
Some refactoring of `Base.hh` has already been split out into #500, so that should be merged first. …
=> dartsim: Add support for joints in worlds

bullet-featherstone/src/ShapeFeatures.cc, bullet-featherstone/src/ShapeFeatures.hh, dartsim/src/ShapeFeatures.cc, dartsim/src/ShapeFeatures.hh, include/gz/physics/EllipsoidShape.hh, include/gz/physics/detail/EllipsoidShape.hh, tpe/plugin/src/ShapeFeatures.cc, tpe/plugin/src/ShapeFeatures.hh
Fixes API issue noted in https://github.com/gazebosim/gz-physics/pull/515#discussion_r1227485794
Pass the Vector of Ellipsoid radii as a `const` reference to `SetRadii` and `AttachEllipsoidShape`. This is either an API or ABI break, so I've targeted `main`.
=> EllipsoidShape: use const references in API

test/common_test/CMakeLists.txt
Fixes #522
As noted in #522, `gz-physics6` will fail to build if certain dependencies required by a component are missing, instead of just skipping those components. I previously noticed this while attempting to make the `gz-common5-geospatial` component optional in #516 but that PR was closed, so I've cherry-picked this build fix on its own.
A question was raised in https://github.com/gazebosim/gz-physics/pull/516/commits/cc9cced8235366fa810493c1fb04311a6a2f4191?w=1#r1242397957 about the use of the `SKIP_*` and `INTERNAL_SKIP_*` variables that are used by `gz-cmake` to indicate whether a component is to be skipped or not. The `INTERNAL_SKIP_*` variables are set by [gz_find_package](https://github.com/gazebosim/gz-cmake/blob/gz-cmake3/cmake/GzFindPackage.cmake#L296) when dependencies …
=> Check that plugin exists before adding common test

.github/ci/packages-jammy.apt, .github/ci/packages.apt
Small follow-up to https://github.com/gazebosim/gz-physics/pull/526
The `packages-focal.apt` file was removed in https://github.com/gazebosim/gz-physics/pull/526, so `packages-jammy.apt` can now be consolidated with `packages.apt`, which is done here.
=> Consolidate packages.apt files

dartsim/src/plugin.cc
=> Unregister collision detectors when the darstim plugin is unloaded

dartsim/src/SDFFeatures.cc
Currently gazebo prints out error messages if the model has a mesh collision. The collision seems to be created fine but gz-physics still prints out an error msg:
```sh
[Err] [SDFFeatures.cc:843] The geometry element of collision [Rock01_Collider_62] couldn't be created
```
When you have lots of mesh collisions in the world like in the [harmonic demo](https://github.com/gazebosim/harmonic_demo), the console is filled with red error msgs.
Taking a similar approach as in https://github.com/gazebosim/gz-physics/pull/452, this PR just downgrades the severity level from error to debug.
=> Reduce error to debug msg for mesh construction

Changelog.md
Port `ign-physics5 ` ➡️  `gz-physics6`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics6...ign-physics5
=> Merge ign-physics5  gz-physics6

test/common_test/joint_features.cc
This sets console verbosity to zero when passing NaN commands in the test to reduce console spam.
Reduces console spam
This removes 2000 lines of console output from the `COMMON_TEST_joint_features_*` tests by setting console verbosity to zero when passing NaN commands.
=> joint_features test: reduce console spam

.github/ci/packages.apt
Part of https://github.com/gazebosim/gz-physics/issues/541
Use libdart-6.13 packages in CI instead of libdart-6.12
=> Use libdart6.13 packages in CI from packages.o.o

Changelog.md, bullet-featherstone/src/Base.hh, bullet-featherstone/src/FreeGroupFeatures.cc, bullet-featherstone/src/JointFeatures.cc, bullet-featherstone/src/SDFFeatures.cc, bullet/src/Base.hh, test/common_test/joint_features.cc
Port gz-physics6 to gz-physics7
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics7...gz-physics6
=> Merge: 6 -> 7

CMakeLists.txt, Changelog.md
Preparation for 7.0.0~pre3 release.
Comparison to 6.5.1: https://github.com/gazebosim/gz-physics/compare/gz-physics6_6.5.1...gz-physics7
=> Prepare for 7.0.0~pre3 Release

CMakeLists.txt, dartsim/src/SimulationFeatures.cc, test/common_test/CMakeLists.txt, test/common_test/simulation_features.cc
Fixes https://github.com/gazebosim/gz-sim/issues/2008
Needed by https://github.com/gazebosim/gz-sim/pull/2178
The implementation of contact constraints in the upstream version of dart uses a different sign due to the order of operands in a cross product. See [dart 6.10 fork](https://github.com/gazebo-forks/dart/blob/f1821780e93f34cdd4c138c1a2b3e558e0e72cbe/dart/constraint/ContactConstraint.cpp#L797) vs [dart 6.13 upstream](
https://github.com/dartsim/dart/blob/9f2d6073b32d7de27b6e1ed29fe6f03bf56043a9/dart/constraint/ContactConstraint.cpp#L782). This PR inverts the sign for velocities in the first and second friction directions if it detects that the upstream version of DART is being used. See also https://github.com/gazebo-forks/dart/pull/33
This also enables a test that was accidentally …
=> dartsim: Fix sign convention error with contact surface motion velocities

tutorials/02_installation.md
Added some info on how to run specific tests, similar to [these instructions](https://github.com/gazebosim/gz-rendering/blob/451e34e46622ab7a8f6aa4d521ba0a1565b8fdb7/tutorials/02_install.md?plain=1#L290-L307) in gz-rendering
=> Add sample ctest cmds to tutorials

bullet-featherstone/src/FreeGroupFeatures.cc, bullet-featherstone/src/KinematicsFeatures.cc, test/common_test/simulation_features.cc
Part of https://github.com/gazebosim/gz-physics/issues/545.
I've been working on a test for off-diagonal moment of inertia components to support https://github.com/gazebosim/gz-physics/pull/544 based on free rotation of oblong rigid bodies (similar to a [test from gazebo-classic](https://github.com/gazebosim/gazebo-classic/blob/7ccef40e24831eb5cd974b489ee279fc064eacc4/test/integration/physics_link.cc#L315-L388)), and I found that bullet-featherstone's `SetFreeGroupWorldAngularVelocity` API wasn't working quite right. I've updated the FeatureList for the FreeGroup test in `COMMON_TEST_simulation_features` so that it will run with bullet-featherstone (https://github.com/gazebosim/gz-physics/commit/33e12fa800e31f563a6806aa0051c2607ccc1347) and also refactored the test a bit …
=> bullet-featherstone: fix setting angular velocity

dartsim/src/SDFFeatures.cc
Backport #351 to citadel, better late than never (https://github.com/gazebosim/gz-physics/pull/351#issuecomment-1201385754)
Original commit message:
dartsim: fix handling inertia matrix pose rotation (#351)
When loading a model from SDF, the moment of inertia matrix is currently applying any rotations in the //inertial/pose two times, since the rotations are applied explicitly, but they are already applied in math::Inertial::Moi.
**Note to maintainers**: Remember to use **Rebase-and-Merge**.
=> Backport #351 to citadel: fix dartsim inertia matrix rotation

.github/workflows/ci.yml, .github/workflows/triage.yml
Port `ign-physics2 ` ➡️  `ign-physics5`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/ign-physics5...ign-physics2
=> Merge ign-physics2 ➡️  ign-physics5

bullet-featherstone/src/Base.hh, test/common_test/world_features.cc, test/common_test/worlds/world_single_nested_model.sdf
Fixes https://github.com/gazebosim/gz-physics/issues/573
When a `btMultiBody` is removed, its joint constraints are never actually removed, causing invalid pointers to be accessed when processing these `btMultiBodyConstraint`s in bullet in the next world step. This PR makes sure all multi body constraints associated with a model are removed properly.
Updated `world_features` test to capture this case. To run the test:
```
ctest -R COMMON_TEST_world_features_bullet-featherstone
```
=> bullet-featherstone: Fix removing model with joints

CMakeLists.txt, dartsim/src/EntityManagementFeatures.hh, dartsim/src/SDFFeatures.hh
Part of testing gazebosim/gz-cmake#392.
=> Use HIDE_SYMBOLS_BY_DEFAULT

.github/workflows/ci.yml
Improves coverage with bullet-featherstone
In #574, some functionality is being added that depends on a version of bullet that is not available on 20.04 but is available on 22.04, macOS and windows (see https://github.com/gazebosim/gz-physics/pull/574#discussion_r1397703321). Some ifdefs are being added to support compilation on 20.04, but computing code coverage on 20.04 will be incomplete. This changes the code coverage and codecheck platforms from 20.04 to 22.04, and CI is still 🟢, so it seems like a safe change.
Observer results of GitHub workflow.
=> CI workflow: use 22.04 for codecheck, coverage

dartsim/src/SDFFeatures.cc
=> Backport mesh construction error to debug msg (#531)

CMakeLists.txt, Changelog.md
Preparation for 2.6.2 release.
Comparison to 2.6.1: https://github.com/gazebosim/gz-physics/compare/ignition-physics2_2.6.1...ign-physics2
=> Prepare for 2.6.2 Release

test/common_test/CMakeLists.txt, test/common_test/joint_transmitted_wrench_features.cc
Split out from #574 with acknowledgement to @iche033
Currently the bullet API is called from a common test to get the bullet version in order to disable portions of a test that require new features of bullet. This moves the version checking to cmake with `VERSION_*` comparison operators and replaces the bullet API call with a macro defined based on that cmake version comparison.
=> Get bullet version from cmake instead of API

.github/workflows/ci.yml, .github/workflows/triage.yml, Changelog.md
Port `ign-physics5 ` ➡️  `gz-physics6`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics6...ign-physics5
=> Merge ign-physics5 ➡️  gz-physics6

.github/workflows/ci.yml, .github/workflows/triage.yml, Changelog.md, bullet-featherstone/src/SDFFeatures.cc, test/common_test/CMakeLists.txt, test/common_test/joint_transmitted_wrench_features.cc
Port `gz-physics6` to `gz-physics7`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics7...gz-physics6
=> Merge 6 ➡️ 7

include/gz/physics/config.hh.in
Part of https://github.com/gazebosim/gz-cmake/issues/412
Ensure that the `GZ_PHYSICS_VERSION_NAMESPACE` macro is defined in `config.hh.in`.
=> Define GZ_PHYSICS_VERSION_NAMESPACE in config.hh

CMakeLists.txt
Fixes https://github.com/gazebosim/gz-physics/issues/595
We need gz-math 6.13 and newer to use `gz` namespaces.
=> Require gz-math 6.13 for ign->gz transition

bullet-featherstone/src/Base.cc, bullet-featherstone/src/SDFFeatures.cc, test/common_test/joint_features.cc
Mesh collisions are quite unstable in our bullet-featherstone implementation. Sometimes they explode and fly away on contact. The bullet-featherstone's multibody constraint solve applies a large impulse (uncapped) when penetration occurs.  To reduce this effect, we tune 2 parameters:
* collision margin - increased from 0.001 to 0.01
* 0.01 is actually the [default margin](https://github.com/bulletphysics/bullet3/blob/6bb8d1123d8a55d407b19fd3357c724d0f5c9d3c/src/BulletCollision/Gimpact/btGImpactShape.h#L530) for GImpact meshes. The new value is also consistent with gazebo-classic which does not have margin set for GImpact meshes (so uses default value of 0.01)
* [erp2](https://github.com/bulletphysics/bullet3/blob/6bb8d1123d8a55d407b19fd3357c724d0f5c9d3c/src/BulletDynamics/ConstraintSolver/ …
=> bullet-featherstone: Improve mesh collision stability

bullet-featherstone/src/Base.cc, bullet-featherstone/src/Base.hh, bullet-featherstone/src/EntityManagementFeatures.cc, bullet-featherstone/src/EntityManagementFeatures.hh, bullet-featherstone/src/FreeGroupFeatures.cc, bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/SDFFeatures.hh, test/common_test/CMakeLists.txt, test/common_test/Worlds.hh, test/common_test/free_joint_features.cc, test/common_test/joint_features.cc, test/common_test/world_features.cc, test/common_test/worlds/world_single_nested_model.sdf
Port gz-physics6 to gz-physics7
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics7...gz-physics6
=> Merge 6 -> 7 

bullet-featherstone/src/Base.cc, bullet-featherstone/src/WorldFeatures.cc, bullet-featherstone/src/WorldFeatures.hh, dartsim/src/WorldFeatures.cc, dartsim/src/WorldFeatures.hh, dartsim/src/WorldFeatures_TEST.cc, include/gz/physics/World.hh, include/gz/physics/detail/World.hh, test/common_test/joint_features.cc, test/common_test/world_features.cc
Extends Solver feature to support setting solver iterations per step.
Added support in:
* dart: only applicable if solver type is `PgsBoxedLcpSolver`
* bullet-featherstone: sets solver iteration for `btMultiBodyMCLPConstraintSolver`.  By default it's now set to 50 (same as the default value in [`//world/physics/bullet/solver/iters`](http://sdformat.org/spec?ver=1.11&elem=physics#solver_iters)). Originally it was only [10](https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/ConstraintSolver/btContactSolverInfo.h#L85). Changing to 50 improves stability and prevents objects from drifting.
=> Support setting solver iterations

bullet-featherstone/src/JointFeatures.cc, test/common_test/joint_features.cc, test/common_test/worlds/joint_across_models.sdf
Fixes attaching fixed joint between 2 models.
When 2 models are attached by a fixed joint in bullet-featherstone, their rotations are not maintained (only the translation was set). This PR fixes the issue.
Before the fix, when you try to create a detachable joint in gz sim (which uses a fixed joint) between two models with rotations, the parent's rotation will be rotated to match the child's, making the models unstable.
I updated the `joint_features` test to use models with rotations.
To test with gz sim: run the [box_attach.sdf](https://gist.github.com/iche033/42731e6cb098d3c79655ac2b70fcbd78) world with bullet-featherstone:
```bash
gz sim -v 4 box_attach.sdf --physics-engine gz-physics-bullet-featherstone-plugin
```
Hit play to create the detachable joint and the boxes become unstable: …
=> [bullet-featherstone] Fix attaching fixed joint

test/common_test/detachable_joint.cc
Related issue: #612
Test started failing recently on hombrew likely due to new ODE 0.6.15 bottle. Disabling check until issue is fixed upstream.
=> Disable check in `DetachableJointTest.CorrectAttachmentPoints` test for dartsim plugin on homebrew

bullet-featherstone/src/SDFFeatures.cc, test/common_test/collisions.cc
Skip collision checking between collisions in 1) a static model 2) a fixed base link, and 3) a non base link with zero dofs.
This is done by setting the collision filter mask / flags to use the `StaticFilter`, which is already done for static objects (`<static>true</static>`), i.e. static objects already ignore collisions with each other.
This is for perf optimization. When you have overlapping complex meshes with fixed world joints, they would cause a perf hit and these changes would allow bullet to skip collision checking between them.
Added a test in `collisions.cc` that checks contacts between static objects and objects with fixed world joint.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining …
=> [bullet-featherstone] Ignore collision between static objects and objects with world joint

test/common_test/joint_features.cc
Part of #620.
As noted in #620, the [JointFeaturesDetachTest/0.JointDetach](https://build.osrfoundation.org/view/gz-harmonic/job/gz_physics-ci-gz-physics7-homebrew-amd64/35/testReport/junit/(root)/JointFeaturesDetachTest_0/JointDetach_2/) test has been failing on macOS since ODE 0.16.5 was merged to homebrew-core in https://github.com/Homebrew/homebrew-core/pull/167158. This disables the failing test expectations while we investigate the cause in #620.
=> Disable test failing due to ODE/libccd

Changelog.md, bullet-featherstone/CMakeLists.txt, bullet-featherstone/src/FreeGroupFeatures.cc, bullet-featherstone/src/JointFeatures.cc, bullet-featherstone/src/SDFFeatures.cc, bullet/CMakeLists.txt, bullet/src/plugin.cc, dartsim/CMakeLists.txt, test/common_test/collisions.cc, test/common_test/free_joint_features.cc, test/common_test/joint_features.cc, test/common_test/worlds/joint_across_models.sdf, tpe/plugin/CMakeLists.txt
Port `gz-physics7 ` ➡️  `main`
Branch comparison: https://github.com/ignitionrobotics/ign-physics/compare/main...gz-physics7
=> Merge gz-physics7 ➡️  main

test/common_test/CMakeLists.txt
Part of gazebosim/gz-cmake#350.
I suggested in https://github.com/gazebosim/gz-cmake/issues/350#issuecomment-1907453341 that we find python directly so that `GzPython` can be deprecated, and this is a step towards that goal.
Compile and run tests and verify that the `check_test_ran.py` script still runs.
=> Find python directly instead of using GzPython

bullet-featherstone/src/Base.cc, test/common_test/joint_features.cc
Disable test failing due to ODE/libccd (#621)
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_physics-ci-gz-physics6-homebrew-amd64&build=40)](https://build.osrfoundation.org/job/gz_physics-ci-gz-physics6-homebrew-amd64/40/) https://build.osrfoundation.org/job/gz_physics-ci-gz-physics6-homebrew-amd64/40/testReport/
Part of #620.
Original PR description
Part of #620.
As noted in #620, the [JointFeaturesDetachTest/0.JointDetach](https://build.osrfoundation.org/view/gz-harmonic/job/gz_physics-ci-gz-physics7-homebrew-amd64/35/testReport/junit/(root)/JointFeaturesDetachTest_0/JointDetach_2/) test has been failing on macOS since ODE 0.16.5 was merged to homebrew-core in https://github.com/Homebrew/homebrew-core/pull/167158. This disables the failing test expectations …
=> Backport #621 to Garden

bullet-featherstone/src/SDFFeatures.cc
After setting a btConvexHullShape's collision margin, the AABBs need to be explicitly recalculated.
This has performance implications. When AABBs overlap, More computation is done in terms of building islands, solving constraints, etc. Non overlapping objects at rest can also be deactivated. So this fix helps improve performance when many objects are located close to each other.
For reference, the same calls are done in the bullet examples, e.g. [here](https://github.com/bulletphysics/bullet3/blob/272c7099d3ba8ac9e8c142e361e8d4cf5d91b8f2/examples/SharedMemory/PhysicsServerCommandProcessor.cpp#L5356-L5357)
The difference in broadphase AABBs is visualized below:
Left: No recalculation (before the changes)
Right: AABB recalculated
The AABB size difference is roughly `[0.1 0.1 0.1]`
Note that …
=> bullet-featherstone: Fix convex hull shape's AABB

bullet-featherstone/src/Base.hh, bullet-featherstone/src/SDFFeatures.cc
Fixes #<NUMBER>
Even with #632 , it looks like objects that are attached to each other continue to generate contacts. Even though we've explicitly marked the two objects not to collide, looking at the bullet code (https://github.com/bulletphysics/bullet3/blob/e9c461b0ace140d5c73972760781d94b7b5eee53/src/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h#L79-L80), that is ignored because `checkCollideWithOverride` will always return true if the two objects are not in the same btMultiBody.
@iche033 I haven't checked this thoroughly, but the solution I came up with is to call the base class's `checkCollideWithOverride` as well as `btMultiBodyLinkCollider::checkCollideWithOverride` and return the result of anding the two. This does behave much better. I tried with the SDF below by …
=> Disable collisions between attached bodies

dartsim/src/JointFeatures_TEST.cc
Fixes CI on physics2 + Homebew, 
Reference: https://build.osrfoundation.org/job/gz_physics-ci-ign-physics2-homebrew-amd64/43/testReport/
Backports: https://github.com/gazebosim/gz-physics/commit/13bf7f50ce0c66d942884b502294014360190e82
It is not a direct backport, because the file was different, and I changed the logic because the tested code is directly in a dartsim folder.
Disable test failing on homebrew and tag issue tracking it
=> Disable test failing due to ODE/libccd (backport #621)

include/gz/physics/detail/InspectFeatures.hh
Fixes #644 
Adds a missing include (algorithm). Needed due to use of std::find.
=> Add missing algorithm include

bullet-featherstone/src/FreeGroupFeatures.cc
Suggestion for #632 
Testing the transform tool on three models attached with a detachable joint shows the problem. Without this change, we observe the previous rotation behavior.
<details><summary>detachable_joint_three_boxes.sdf</summary>
<p>
```xml
<?xml version="1.0"?>
<sdf version="1.11">
<world name="default">
<light type="directional" name="sun">
<cast_shadows>true</cast_shadows>
<pose>0 0 10 0 0 0</pose>
<diffuse>1 1 1 1</diffuse>
<specular>0.5 0.5 0.5 1</specular>
<attenuation>
<range>1000</range>
<constant>0.9</constant>
<linear>0.01</linear>
<quadratic>0.001</quadratic>
</attenuation>
<direction>-0.5 0.1 -0.9</direction>
</light>
<model name="ground_plane">
<static>true</static>
<link name="link">
<collision name="collision">
<geometry>
<plane>
<normal>0 0 1</normal>
</plane> …
```
=> Enforce fixed constraints recursively when setting pose on freegroups

bullet-featherstone/src/KinematicsFeatures.cc, bullet-featherstone/src/KinematicsFeatures.hh, bullet-featherstone/src/ShapeFeatures.cc, test/common_test/Worlds.hh, test/common_test/kinematic_features.cc, test/common_test/link_features.cc, test/common_test/worlds/pose_offset.sdf
hide whitespace changes for better diff:
https://github.com/gazebosim/gz-physics/pull/647/files?w=1
Currently if a collision has a pose offset, the bullet-featherstone plugin return an incorrect axis aligned bounding box for the link containing the collision. This is found to be caused by incorrect frame data pose computed for collisions - It currently ignores the collision pose offset. 
This PR makes a few changes to `KinematicsFeatures::FrameDataRelativeToWorld` in bullet-featherstone plugin:
* fixed getting collision pose relative to world
* fixed getting model pose relative to world
* minor refactoring
The link_features's bounding box test was previously skipped for bullet-featherstone plugin. This PR enables this test for bullet-featherstone by requiring only a minimal set of …
=> bullet-featherstone: Fix bounding box for collisions with pose offset

dartsim/src/SDFFeatures.cc, dartsim/src/WorldFeatures_TEST.cc, dartsim/worlds/falling.world
Original issue: gazebosim/gz-sim#504
Add parsing and support for no gravity link when using DartSim engine
For implementation and test details, see gazebosim/gz-sim#2398
Changes in other repo:
gz-physics: gazebosim/gz-physics#633
sdformat: gazebosim/sdformat#1410
=> Add no gravity link support

README.md, bullet-featherstone/README.md, bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/ShapeFeatures.cc, bullet-featherstone/src/ShapeFeatures.hh, bullet/src/SDFFeatures.cc, dartsim/src/CustomConeMeshShape.cc, dartsim/src/CustomConeMeshShape.hh, dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures_TEST.cc, dartsim/src/ShapeFeatures.cc, dartsim/src/ShapeFeatures.hh, include/gz/physics/ConeShape.hh, include/gz/physics/detail/ConeShape.hh, test/common_test/simulation_features.cc, test/common_test/worlds/shapes.world, tpe/lib/src/Collision.cc, tpe/lib/src/Shape.cc, tpe/lib/src/Shape.hh, tpe/plugin/src/SDFFeatures.cc, tpe/plugin/src/ShapeFeatures.cc, tpe/plugin/src/ShapeFeatures.hh, tpe/plugin/src/SimulationFeatures_TEST.cc
This helps add the missing cone geometry for primitive/basic parametric shapes:
And is also valuable for visualizations of emitters/source that typically have conic-based spread as seen in this acoustic attack on an IMU by showing the affected area:
Associated PRs:
- https://github.com/gazebosim/gz-gui/pull/621
- https://github.com/gazebosim/gz-math/pull/594
- https://github.com/gazebosim/gz-msgs/pull/442
- https://github.com/gazebosim/gz-physics/pull/639
- https://github.com/gazebosim/gz-rendering/pull/1003
- https://github.com/gazebosim/gz-sim/pull/2410
- https://github.com/gazebosim/sdformat/pull/1418
=> Add Cone as a collision shape

bullet-featherstone/src/JointFeatures.cc, test/common_test/worlds/detachable_joint.world
When creating a fixed constraint between links, the `SetJointTransformFromParent` currently does not take into account the inertial pose. If an inertial pose offset exists, the fixed constraint causes the 2 models to be displaced from their original position. This PR updates the calculation in `SetJointTransformFromParent` to include inertial pose offset. 
The `detachable_joint.world` test world is updated to use a model with inertial pose offset - this world is used by the `CorrectAttachmentPoints` test in `detachable_joint` common test. The test fails without the changes in this PR.
=> bullet-featherstone: Fix attaching fixed joint between models with inertial pose offset

bullet-featherstone/src/SDFFeatures.cc
Makes use of the voxel resolution SDF param added in https://github.com/gazebosim/sdformat/pull/1429. 
see screenshot of a mesh with different voxel resolutions in https://github.com/gazebosim/gz-sim/pull/2445
=> bullet-featherstone: Parse voxel resolution SDF param when decomposing meshes

README.md, bullet-featherstone/README.md, bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/ShapeFeatures.cc, bullet-featherstone/src/ShapeFeatures.hh, bullet/src/SDFFeatures.cc, dartsim/src/CustomConeMeshShape.cc, dartsim/src/CustomConeMeshShape.hh, dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures_TEST.cc, dartsim/src/ShapeFeatures.cc, dartsim/src/ShapeFeatures.hh, include/gz/physics/ConeShape.hh, include/gz/physics/detail/ConeShape.hh, test/common_test/joint_features.cc, test/common_test/simulation_features.cc, test/common_test/worlds/shapes.world, tpe/lib/src/Collision.cc, tpe/lib/src/Shape.cc, tpe/lib/src/Shape.hh, tpe/plugin/src/SDFFeatures.cc, tpe/plugin/src/ShapeFeatures.cc, tpe/plugin/src/ShapeFeatures.hh, tpe/plugin/src/SimulationFeatures_TEST.cc
This helps add the missing cone geometry for primitive/basic parametric shapes:
And is also valuable for visualizations of emitters/source that typically have conic-based spread as seen in this acoustic attack on an IMU by showing the affected area:
Associated PRs:
- https://github.com/gazebosim/gz-gui/pull/620
- https://github.com/gazebosim/gz-math/pull/593
- https://github.com/gazebosim/gz-msgs/pull/441
- https://github.com/gazebosim/gz-physics/pull/638
- https://github.com/gazebosim/gz-rendering/pull/1001
- https://github.com/gazebosim/gz-sim/pull/2404
- https://github.com/gazebosim/sdformat/pull/1415
=> Add Cone as a primitive parametric shape.

bullet-featherstone/src/JointFeatures.cc
Fixes the following error when compiling with the `-Wctad-maybe-unsupported` flag
```sh
physics/bullet_featherstone/src/JointFeatures.cc:179:7: error: 'math::Vector3' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
```
=> Fix CTAD compile warnings

bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/SDFFeatures.hh, test/common_test/worlds/test.world
It was found that empty links connected by joints do not respond to joint commands as they do not have a collision object associated with it. This PR fixes the issue by initializing a link collider with an empty compound shape for links without collisions.
I refactored the code for creating a link collider into its own helper function.
Previously collisions were added to empty links in test.world in #658 and that allowed joint vel control tests to pass. This is no longer necessary. I removed those collisions and the tests should still pass.
=> bullet-featherstone: Support empty links

.github/workflows/package_xml.yml, CMakeLists.txt, bullet-featherstone/src/Base.hh, bullet-featherstone/src/FreeGroupFeatures.cc, bullet-featherstone/src/JointFeatures.cc, bullet-featherstone/src/KinematicsFeatures.cc, bullet-featherstone/src/KinematicsFeatures.hh, bullet-featherstone/src/LinkFeatures.cc, bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/ShapeFeatures.cc, bullet-featherstone/src/SimulationFeatures.cc, dartsim/src/SimulationFeatures.cc, dartsim/src/SimulationFeatures.hh, include/gz/physics/GetRayIntersection.hh, include/gz/physics/detail/GetRayIntersection.hh, include/gz/physics/detail/InspectFeatures.hh, package.xml, test/common_test/CMakeLists.txt, test/common_test/Worlds.hh, test/common_test/joint_features.cc, test/common_test/kinematic_features.cc, test/common_test/link_features.cc, test/common_test/simulation_features.cc, test/common_test/worlds/detachable_joint.world, test/common_test/worlds/joint_across_models_fixed.sdf, test/common_test/worlds/pose_offset.sdf
Port gz-physics7 as of https://github.com/gazebosim/gz-physics/commit/6bcf1af48b016a1e8300e0eed6dcd008fa044cea to main
The conflicts were difficult to resolve, due to some changes in https://github.com/gazebosim/gz-physics/commit/a1cb98905ddce83379b3f8367b3c1fd3c7ffb8fb, so I'm splitting this merge into two parts, first merging with the commit just before that one.
Branch comparison: https://github.com/gazebosim/gz-physics/compare/main...6bcf1af48b016a1e8300e0eed6dcd008fa044cea
=> Merge gz-physics7 ➡️ main: part 1

.github/workflows/ci.yml, CMakeLists.txt, README.md, examples/hello_world_loader/CMakeLists.txt, examples/hello_world_plugin/CMakeLists.txt, examples/simple_plugin/CMakeLists.txt
Part of gazebosim/gz-cmake#350.
This adds a GitHub workflow using Noble and increases our minimum required cmake version to 3.22.1 since we are already requiring that in gz-cmake4.
It also fixes the push branch regex to support multi-digit versions (copied from https://github.com/gazebosim/sdformat/pull/1445) and fixes the CI badges in the README.
Check CI results
=> Enable 24.04 CI, require cmake 3.22.1

include/gz/physics/FreeGroup.hh, include/gz/physics/detail/FreeGroup.hh, test/common_test/simulation_features.cc, tpe/plugin/src/SimulationFeatures_TEST.cc
Remove `CanonicalLink()` in `FreeGroup`. It's replaced by `RootLink()`.
=> Remove deprecated function

CMakeLists.txt, Changelog.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1092
Update changelog for gz-physics 8.0.0, with an unspecified release date.
Compare to https://github.com/gazebosim/gz-physics/compare/gz-physics7_7.3.0...main
Note: I excluded the following Harmonic PRs that have not been released as of 7.3.0 since they will be released in Harmonic. Please advise if I should add them.
* https://github.com/gazebosim/gz-physics/pull/658
* #663
* #665
=> Ionic Changelog

README.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1092
Update branch references in the README from `main` to `gz-physics8` including the jenkins badges, an example `git` command, and a markdown links.
=> README: update references from main to gz-physics8

README.md
Fixes #<NUMBER>
The installation tutorial link in README is broken. This updates the link to point to the latest installation tutorial page.
=> Fix installation tutorial link in README

tutorials/08-implementing-a-custom-feature.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1425
The paths and directory listings in the tutorial were outdated. This PR fixes it.
=> tutorials/08-implementing-a-custom-feature: Fixed paths and directory listings

tutorials/09_use_custom_engine.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1428
The tutorial included wrong instructions for building the example. This PR fixes that.
=> tutorials/09_use_custom_engine: Add actual build&run instructions

tutorials/02_installation.md
Similar fix as https://github.com/gazebosim/gz-rendering/pull/1064. The ruby command no longer works. Updated to point to homebrew website for installation instructions.
=> Update homebrew install instruction

CMakeLists.txt, Changelog.md, README.md, examples/hello_world_loader/CMakeLists.txt, examples/hello_world_plugin/CMakeLists.txt, examples/simple_plugin/CMakeLists.txt, package.xml, tutorials/06-physics-simulation-concepts.md, tutorials/07-implementing-a-physics-plugin.md, tutorials/08-implementing-a-custom-feature.md
Bump main to gz-physics 9.0.0~pre1
=> Bump main to physics 9.0.0~pre1

bullet-featherstone/src/FreeGroupFeatures.cc, bullet-featherstone/src/SDFFeatures.cc, test/common_test/free_joint_features.cc
Fixes https://github.com/gazebosim/gz-sim/issues/2663
Finding free group for a body that has a fixed base results an invalid ID, which causes set world pose from gz-sim to fail, see https://github.com/gazebosim/gz-sim/issues/2663. This PR removes the fixed base body check and I verified that set world pose works for a body with fixed base.  
Another minor change - I noticed that finding free group for links has the same check. Currently free groups only works for models in bullet-featherstone so I updated the function to just call `FindFreeGroupForModel`.
=> bullet-featherstone: Fix finding free group for a body with fixed base

dartsim/src/Base.hh, dartsim/src/SimulationFeatures.cc
Fixes https://github.com/gazebosim/gz-physics/issues/661
DART seems to compute invalid poses for certain objects (e.g. Capsule, Ellipse) with large accelerations. The computed poses end up with `nan` values resulting in a crash. This patch detects this condition and reassigns the poses to the last known poses and resets velocities to zero to prevent the crash.
```
gz sim -v4 rolling_shapes.sdf -z 1000000 -s -r
```
=> Prevent crash when objects move to invalid poses

CMakeLists.txt, Migration.md, dartsim/src/SDFFeatures_TEST.cc, include/gz/physics/config.hh.in
Perform the tock of the tick-tock cycle and remove / move deprecated code.
=> Remove deprecations: tock

bullet-featherstone/src/JointFeatures.cc, test/common_test/joint_features.cc
Fixes https://github.com/gazebosim/gz-sim/issues/2729
Currently the joint motor responsible for enforcing a joint vel cmd does not disengage when a force command is received. This PR fixes the issue by removing the joint motor constraint whenever a joint force cmd is received.
=> bullet-featherstone: Remove joint motor constraint on joint force cmd

dartsim/src/SimulationFeatures.hh, test/integration/DoublePendulum.cc
Fixes windows warnings
https://build.osrfoundation.org/job/gz_physics-8-clowin/15/msbuild/
* https://github.com/gazebosim/gz-physics/commit/353811df0ed227bdea3624b5fd7e4b15a3208bef: use `static_cast` to fix a windows type conversion warning
* https://github.com/gazebosim/gz-physics/commit/dd37b50a33954c6e96dab24d40cdaa1a48734845: the `dart::collision::Contact` is [defined as a struct](https://github.com/dartsim/dart/blob/main/dart/collision/Contact.hpp#L46), so fix the forward declaration
=> Fix windows warnings

bullet-featherstone/src/Base.cc, bullet-featherstone/src/Base.hh, bullet-featherstone/src/FreeGroupFeatures.cc, bullet-featherstone/src/JointFeatures.cc, bullet-featherstone/src/SDFFeatures.cc, bullet-featherstone/src/SimulationFeatures.cc, test/common_test/collisions.cc, test/common_test/joint_features.cc, test/common_test/world_features.cc
Fixes three issues in bullet-featherstone plugin:
1. After calling `SetPosition` to set a joint position, incorrect collision transforms are used in the next forward step
2. After calling `SetWorldPose` to set the pose of a FreeGroup, incorrect collision transforms are used in the next forward step
3. Collisions are ignored between a static object and any link on a fixed-base model that is a child of a fixed joint
Added a `GzMultiBody` wrapper for `btMultiBody` to ensure that a flag is set whenever joint position is set or base transform is set indicating that collision transforms need to be updated. Then collision transforms are updated in the next forward step for any body which has the flag set, and the flag is reset.
For bug 3 above, I updated `SDFFeatures::CreateLinkCollider` to …
=> Fix collision checking issues in bullet-featherstone

dartsim/src/WorldFeatures.cc, test/plugins/DARTDoublePendulum.cc
Fixes macOS CI
There are compiler warnings coming from octomap on homebrew when compiling dartsim. The warning has been reported upstream at https://github.com/OctoMap/octomap/issues/431. For now suppress the warning.
This is a little messy since it uses macros defined in the `gz/utils/detail/` folder instead of the official API in `gz/utils/SuppressWarning.hh`, but there is currently no supported macro for suppressing this type of warning. I'll open a feature request in gz-utils to provide more flexible macros.
=> Suppress -Wreturn-type warning from octomap

bullet-featherstone/CMakeLists.txt, bullet/CMakeLists.txt, dartsim/CMakeLists.txt, tpe/plugin/CMakeLists.txt
Fixes gz-sim test failures with PR chain in https://github.com/gazebosim/gz-sim/pull/2910, part of https://github.com/gazebo-tooling/release-tools/issues/1309
When testing the remaining Jetty version bumps (such as https://github.com/gazebosim/gz-sim/pull/2910), I ran a colcon build:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ci__colcon_any-manual_ubuntu_noble_amd64&build=34)](https://build.osrfoundation.org/job/ci__colcon_any-manual_ubuntu_noble_amd64/34/) https://build.osrfoundation.org/job/ci__colcon_any-manual_ubuntu_noble_amd64/34/
and noticed two gz-sim test failures in particular the seem related to symlinked physics plugins:
* [INTEGRATION_pose_publisher_system](https://build.osrfoundation.org/job/ci__colcon_any-manual_ubuntu_noble_amd64/34/testReport/p …
=> Remove symlink loops in engine-plugins

BUILD.bazel
Fixes a downstream linker error in gz-sim when building the physics system, which uses the `getEngineInstallDir` method as a fallback to find the physics engine plugin lib. The `getEngineInstallDir` method is implemented in `src/InstallationDirectories.cc`, so it needs to be included under `srcs` in the `gz-physics` library target.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> [Bazel] Fix missing symbol for getEngineInstallDir

dartsim/src/SDFFeatures.cc, dartsim/src/SDFFeatures_TEST.cc, test/common_test/worlds/test.world, tpe/plugin/src/SDFFeatures_TEST.cc
Closes #634
Allow joint properties to be applied to ball joints in the dart sim physics engine.
As suggested in https://github.com/gazebosim/gz-physics/issues/634, the properties from the first `<axis>` field in the ball joint are applied to all DoF if this element is set. Otherwise the defaults are used, which is current behaviour.
- Add an `<axis>` element to a model using a ball joint and set some of the properties (eg. `<limit>`).
- Prior to the change the property would have no effect, after the change the joint range should be restricted.
- Modify the `wind.sdf` model to include `<axis>` elements for each sphere restricting the movement:
```xml
<joint name="sphere_1_joint" type="ball">
<parent>roof</parent>
<child>sphere_1</child>
<axis>
<limit>
<lower>0</lower>
<upper>0</upper> …
```
=> BallJoint: apply axis properties to ball joints

dartsim/src/KinematicsFeatures.cc, test/common_test/kinematic_features.cc
Fix ModelFrameSemantics in dartsim. When a model is added to dartsim, a model [frame](https://github.com/gazebosim/gz-physics/blob/8bcb176e081499d58f230a7df460cffae9e96d11/dartsim/src/SDFFeatures.cc#L568-L571) is also always created. So it looks like we can just look up frames to retrieve model frame data in `KinematicsFeature` instead of using the root body node (which may be at an offset from the model).
Enabled checks for model frame data  in `kinematic_features`
=> Fix model frame data

.github/workflows/bazel.yml, README.md, tutorials/03_physics_plugins.md, tutorials/05_plugin_loading.md, tutorials/08-implementing-a-custom-feature.md, tutorials/09_use_custom_engine.md
Part of https://github.com/gazebosim/gz-jetty/issues/29.
Replace references to `main` branch with `gz-physics9`.
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Replace main branch with gz-physics9

tutorials/07-implementing-a-physics-plugin.md
Found this issue where the command to implement our custom physics plugin was wrong, due to the wrong folder name. This PR fixes it.
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Fix path in physics plugin implementation tutorial

tutorials/06-physics-simulation-concepts.md
This is a minor spelling fix in the documentation. No testing is necessary. 
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Fix spelling in simulation concepts tutorial

tutorials/09_use_custom_engine.md
When building with the current instructions, it builds just the `PluginTest` but does not build the `libSimplePlugin.so`, resulting in the following message when running:
```
Error while loading the library [gz-physics/examples/simple_plugin/build/libSimplePlugin.so]: gz-physics/examples/simple_plugin/build/libSimplePlugin.so: cannot open shared object file: No such file or directory
Something went wrong, the engine is null
```
Instead of building just `PluginTest`, this PR switches to just using make to build everything. We could alternatively use `cmake --build .` without the `--target` to build everything. 
This was tested by following the tutorial and building the simple plugin example and getting a successful message:
```
Created empty world!
```
**Note to maintainers**: Remember to …
=> Update 09_use_custom_engine.md build commands

dartsim/src/Base.hh, dartsim/src/EntityManagementFeatures.cc
Fixes gazebosim/gz-sim#3080
This PR fixes a crash that could occur when recursively deleting nested models if the parent `world` or `model` no longer exists.
Deleting a nested model without checking the validity of its `world` or parent `model` could lead to invalid access and a crash. Existence checks are added before deletion, ensuring safe and robust recursive removal of models.
=> Fix crash when recursively deleting nested models

tutorials/06-physics-simulation-concepts.md, tutorials/07-implementing-a-physics-plugin.md, tutorials/09_use_custom_engine.md
This is a collection of fixes from the Jetty tutorial party to backport to Ionic:
* #777 
* #778 
* #780
Use Rebase-and-merge
=> Backport tutorial party fixes
