CONTRIBUTING.md
Changelog.md
README.md
bitbucket-pipelines.yml
dartsim/src/EntityManagementFeatures.cc
tutorials/02_installation.md

Signed-off-by: Louise Poubel <louise@openrobotics.org>

[master] Update BitBucket links

---

CONTRIBUTING.md
Changelog.md
README.md
bitbucket-pipelines.yml
tutorials/02_installation.md

Signed-off-by: Louise Poubel <louise@openrobotics.org>

[ign-physics2] Update BitBucket links

---

CONTRIBUTING.md
Changelog.md
README.md
bitbucket-pipelines.yml
dartsim/src/Collisions_TEST.cc
dartsim/src/EntityManagementFeatures.cc
tutorials/02_installation.md

Signed-off-by: Louise Poubel <louise@openrobotics.org>

[ign-physics1] Update BitBucket links

---

.github/CODEOWNERS

Signed-off-by: Steven Peters <scpeters@openrobotics.org>

Add CODEOWNERS (cherry-pick of #43 -> ign-physics2)

---

.github/CODEOWNERS

Signed-off-by: Steven Peters <scpeters@openrobotics.org>

Add CODEOWNERS (cherry-pick #43 -> ign-physics1)

---

.github/workflows/ci-bionic.yml
.github/workflows/pr-collection-labeler.yml
.github/workflows/triage.yml
README.md

* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update codecov badge

[ign-physics1] Workflow updates

---

.github/workflows/ci-bionic.yml
.github/workflows/pr-collection-labeler.yml
.github/workflows/triage.yml
README.md

* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges

[ign-physics2] Workflow updates

---

.github/workflows/ci-bionic.yml
.github/workflows/pr-collection-labeler.yml
.github/workflows/triage.yml
README.md

* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges

[master] Workflow updates

---

BUILD.bazel
dartsim/BUILD.bazel
tpe/BUILD.bazel

Signed-off-by: John Shepherd <john@openrobotics.org>

Add gn export headers

---

BUILD.bazel
dartsim/BUILD.bazel
test/PhysicsPluginsList.hh
tpe/BUILD.bazel

Tweaks to support physics plugin loading in gazebo

---

CMakeLists.txt
Changelog.md

Waiting on #56.
Signed-off-by: Nate Koenig <nate@openrobotics.org>

Preparing for 1.9.0 release

---

examples/hello_world_loader/CMakeLists.txt
examples/hello_world_plugin/CMakeLists.txt

Bumped examples to ign-physics3

---

bullet/src/EntityManagementFeatures.cc
bullet/src/EntityManagementFeatures.hh
bullet/src/SDFFeatures.cc
bullet/src/SDFFeatures.hh
bullet/src/plugin.cc

Basic SDF features to allow the first simulation run, iterative work on the devel_bullet branch
Signed-off-by: lobotuerk <jtlorente@ekumenlabs.com>

[Bullet] SDF features (bullet developing)

---

bullet/src/EntityManagementFeatures.cc
bullet/src/EntityManagementFeatures.hh

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

[bullet] Add RemoveEntities features

---

bullet/src/KinematicsFeatures.cc
bullet/src/KinematicsFeatures.hh
bullet/src/plugin.cc

KinematicsFeatures detected by ignition.
Will rebase after https://github.com/ignitionrobotics/ign-physics/pull/136 gets merged.

[Bullet] Kinematics Features

---

bullet/src/SDFFeatures.cc
bullet/src/SDFFeatures.hh

Signed-off-by: lobotuerk <jtlorente@ekumenlabs.com>

[Bullet] Fixed static calculation

---

dartsim/src/JointFeatures.cc
dartsim/src/JointFeatures_TEST.cc

Merge ign-physics1 -> ign-physics2

---

dartsim/src/JointFeatures.cc
dartsim/src/JointFeatures_TEST.cc

Merge forward #137. Checking CI.

Merge ign-physics2 -> ign-physics3

---

bullet/src/EntityManagementFeatures.cc

Signed-off-by: lobotuerk <jtlorente@ekumenlabs.com>

[Bullet] Fixed RemoveModel

---

dartsim/src/CustomMeshShape.cc
dartsim/src/EntityManagementFeatures.cc
dartsim/src/SDFFeatures.cc
dartsim/src/ShapeFeatures.cc
include/ignition/physics/Cloneable.hh
include/ignition/physics/RelativeQuantity.hh

This PR is meant to resolve new codecheck issues introduced by https://github.com/ignitionrobotics/ign-cmake/pull/117.
From my understanding, the plan is to forward port the fixes here to all other ignition versions once https://github.com/ignitionrobotics/ign-cmake/pull/117 is merged.
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

Resolve updated codecheck issues

---

CMakeLists.txt
Changelog.md

Signed-off-by: Addisu Z. Taddese <addisu@openrobotics.org>

Preparing for 1.10 release

---

bullet/src/SimulationFeatures.cc
bullet/src/SimulationFeatures.hh

Signed-off-by: Lobotuerk <jtlorente@ekumenlabs.com>

Added Simulation Features

---

bullet/src/Base.hh
bullet/src/EntityManagementFeatures.cc
bullet/src/SDFFeatures.cc
bullet/src/SDFFeatures.hh
bullet/src/plugin.cc

Changing internal base representation, and adding features to add/remove links

[Bullet] Bullet classic, Add sdf entities

---

bullet/src/Base.hh
bullet/src/FreeGroupFeatures.cc
bullet/src/FreeGroupFeatures.hh
bullet/src/SDFFeatures.cc
bullet/src/plugin.cc

Signed-off-by: Lobotuerk <jtlorente@ekumenlabs.com>

Free Group Feature

---

bullet/src/Base.hh
bullet/src/EntityManagementFeatures.cc
bullet/src/KinematicsFeatures.cc
bullet/src/SDFFeatures.cc

Signed-off-by: Tomas Lorente <jtlorente@ekumenlabs.com>
-Fixed position by adding the base model position into the equiation.
-Fixed gravity by adding an empty collisionshape into the bodies.
-Added a motion state to get the position out of bullet.
-Changed some autos into their proper variable.

[bullet] Basic Features

---

include/ignition/physics/BoxShape.hh
include/ignition/physics/CylinderShape.hh
include/ignition/physics/PlaneShape.hh
include/ignition/physics/SphereShape.hh

Signed-off-by: anindex <an.thai.le97@gmail.com>
From issue #9

API documentation common Attach* features

---

bullet/src/JointFeatures.cc
bullet/src/SDFFeatures.cc

This PR addresses three things:
* Solves a problem with the axis of revolute joints.
* Adds support for fixed joints
* Add some basic getters for revolute joints

[bullet] Getters for revolute joints

---

include/ignition/physics/BoxShape.hh
include/ignition/physics/ConstructEmpty.hh
include/ignition/physics/CylinderShape.hh
include/ignition/physics/GetBoundingBox.hh
include/ignition/physics/GetEntities.hh
include/ignition/physics/Joint.hh
include/ignition/physics/PlaneShape.hh
include/ignition/physics/Shape.hh
include/ignition/physics/SphereShape.hh
tutorials.md.in
tutorials/01_intro.md
tutorials/02_installation.md
tutorials/04-switching-physics-engines.md
tutorials/05_plugin_loading.md
tutorials/06-physics-simulation-concepts.md
tutorials/07-implementing-a-physics-plugin.md
tutorials/08-implementing-a-custom-feature.md
tutorials/09-set-up-physics-engine-tpe.md

Back port tutorials and API doc to citadel to show on website

[Dome] Ign-physics tutorials and API doc back port

---

.github/ci/packages.apt
CMakeLists.txt
Migration.md
include/ignition/physics/CompositeData.hh
include/ignition/physics/FrameID.hh
include/ignition/physics/detail/CompositeData.hh
include/ignition/physics/detail/Identity.hh
src/CMakeLists.txt
tpe/lib/src/AABBTree.hh
tpe/lib/src/CollisionDetector.hh
tpe/lib/src/Engine.hh
tpe/lib/src/Model.hh
tpe/lib/src/Shape.hh
tpe/lib/src/World.hh

Closes #198 and will assist with #50.
Add dependency on ignition-utils1 and its `cli` component. The cli component will help with implementing #50.
See if it compiles and passes CI.
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+archived%3Afalse+)
to support the maintainers

Depend on ignition-utils1 cli component

---

.github/ci/packages.apt
CMakeLists.txt
bitbucket-pipelines.yml

Addresses https://github.com/ignition-tooling/release-tools/issues/361

Bump in edifice: ign-common4

---

.github/ci/packages.apt

Part of https://github.com/ignition-tooling/release-tools/issues/406
The debs have been renamed
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+)
to support the maintainers

ign-utils -> ign-utils1

---

.github/workflows/ci.yml
README.md
tutorials/03_physics_plugins.md
tutorials/06-physics-simulation-concepts.md
tutorials/08-implementing-a-custom-feature.md

Part of  https://github.com/ignition-tooling/release-tools/issues/416
Update all usage of `master`

Master branch updates

---

bullet/src/Base.hh
bullet/src/KinematicsFeatures.cc
bullet/src/SDFFeatures.cc
bullet/src/ShapeFeatures.cc

Should resolve https://github.com/ignitionrobotics/ign-physics/pull/208#discussion_r592823935
Updated Bullet's pose calculation to also use the `Pose` element of the `<inertial>` sdf tag.
No idea, open for suggestions
🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

[Bullet] Inertial Pose Update

---

.github/ci/packages-bionic.apt
.github/ci/packages-focal.apt

Needed to fix building from source.
I'm not sure why CI didn't catch this on https://github.com/ignitionrobotics/ign-physics/pull/225.

Add dart-bullet dependency to CI

---

bullet/src/Base.hh
bullet/src/EntityManagementFeatures.cc
bullet/src/SDFFeatures.cc
bullet/src/ShapeFeatures.cc

This PR addresses comment: https://github.com/ignitionrobotics/ign-physics/pull/208#discussion_r600856533
@Lobotuerk PTAL.
Update: 407a6c8 fixes the segfaults, it was an implementation problem. Ready to merge to the `Bullet` branch.

[Bullet] Auxiliar PR to add index to identity conversion

---

CMakeLists.txt
Changelog.md

Preparation for 3.3.0~pre1 release. Making a pre-release to test new Bullet component.
Comparison to <x.y.z>: https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics3_3.2.0...ign-physics3

🎈 3.3.0~pre1

---

dartsim/src/SDFFeatures.cc

Addressing https://github.com/ignitionrobotics/ign-physics/pull/276#discussion_r671573211

Remove outdated comment

---

.github/CODEOWNERS

Adds @azeey  and myself as Code Owners and removes Marya.

Add azeey and scpeters as code owners

---

CMakeLists.txt
Changelog.md

Preparation for 3.4.1 release.
Comparison to 3.4.0: https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics3_3.4.0...ign-physics3
This will be the final Dome release before EOL

Prepare for 3.4.1 release

---

dartsim/src/JointFeatures_TEST.cc
dartsim/src/KinematicsFeatures_TEST.cc
dartsim/src/LinkFeatures_TEST.cc
dartsim/src/ShapeFeatures_TEST.cc

Backport #325 to citadel. Use rebase-and-merge.

Fix Apache license version (backport to citadel)

---

.github/ci/packages-jammy.apt
.github/workflows/ci.yml
Changelog.md
dartsim/src/JointFeatures_TEST.cc
dartsim/src/KinematicsFeatures_TEST.cc
dartsim/src/LinkFeatures_TEST.cc
dartsim/src/ShapeFeatures_TEST.cc
dartsim/src/WorldFeatures_TEST.cc
examples/hello_world_loader/CMakeLists.txt
examples/hello_world_plugin/CMakeLists.txt
examples/simple_plugin/CMakeLists.txt

Port ign-physics5 to main
Branch comparison: https://github.com/ignitionrobotics/ign-physics/compare/main...ign-physics5

Merge 5 -> main

---

examples/hello_world_loader/CMakeLists.txt
examples/hello_world_plugin/CMakeLists.txt
examples/simple_plugin/CMakeLists.txt

Related to https://github.com/ignition-tooling/release-tools/pull/700
Use `*_VERSION_MAJOR` variables to aid search/replace scripts.

examples: fix cmake find version variables

---

tpe/lib/src/Link.hh

Looks like a left-over from 
* https://github.com/ignitionrobotics/ign-physics/pull/213

Use SuppressWarning from ign-utils

---

.github/ci/packages.apt
CMakeLists.txt
examples/hello_world_loader/CMakeLists.txt
examples/hello_world_plugin/CMakeLists.txt
examples/simple_plugin/CMakeLists.txt
tpe/lib/src/Link.hh

See https://github.com/ignition-tooling/release-tools/issues/685

Bumps in garden : ign-physics6

---

Changelog.md
Migration.md
README.md
api.md.in
dartsim/src/SDFFeatures.cc
dartsim/src/SDFFeatures_TEST.cc
examples/hello_world_loader/CMakeLists.txt
examples/hello_world_loader/README.md
examples/hello_world_plugin/CMakeLists.txt
examples/hello_world_plugin/README.md
examples/simple_plugin/CMakeLists.txt
tpe/plugin/src/FreeGroupFeatures.cc
tutorials.md.in
tutorials/01_intro.md
tutorials/02_installation.md
tutorials/03_physics_plugins.md
tutorials/04-switching-physics-engines.md
tutorials/05_plugin_loading.md
tutorials/06-physics-simulation-concepts.md
tutorials/07-implementing-a-physics-plugin.md
tutorials/08-implementing-a-custom-feature.md
tutorials/09-set-up-physics-engine-tpe.md
tutorials/09_use_custom_engine.md

See: https://github.com/gazebo-tooling/release-tools/issues/757

ign -> gz Partial Docs Migration and Project Name Followups : gz-physics

---

CMakeLists.txt
Changelog.md

Signed-off-by: Ian Chen <ichen@osrfoundation.org>
Preparation for 5.2.0 release.
Comparison to 5.1.0: https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics5_5.1.0...prep_5.2.0

Prepare for 5.2.0 release

---

README.md
dartsim/src/SDFFeatures_TEST.cc

Update CI badges
Point to CI badges for `gz-physics6` branch.
I've made this from a specially named branch in order to test an sdformat branch:
* https://github.com/osrf/homebrew-simulation/commit/950786976e5df77c8bf822cfbed07a83ef476f76
* https://github.com/gazebosim/sdformat/commit/d057b07b8c462410cf6d59b70be4b021bff20bc5

README: update CI badges, fix expected joint limits

---

codecov.yml

Updated Codecov ignored files

---

dartsim/src/SDFFeatures_TEST.cc

Related with https://github.com/gazebosim/sdformat/pull/1112
Fixed Dartsim SDFFeatures_TEST

Fixed Dartsim SDFFeatures_TEST

---

codecov.yml

Reverts gazebosim/gz-physics#406

Revert "Updated Codecov ignored files"

---

tutorials/06-physics-simulation-concepts.md

Updated link in `06-physics-simulation-concepts` instructions. Related https://github.com/gazebosim/garden-tutorial-party/issues/313

Updated 06-physics-simulation-concepts instructions

---

bullet-featherstone/src/SDFFeatures.cc

Bullet-featherstone: Refactor joint code

---

README.md
bullet-featherstone/README.md

Document relevant bullet-featherstone changes/features before releasing

Add top-level bullet-featherstone README

---

dartsim/src/Base.hh
dartsim/src/SimulationFeatures.cc

Cherry-picked #465.
**Note to maintainers**: Remember to **Rebase and merge**  (not squash-merge or merge commit)

Fix build errors and warnings for DART 6.13.0 (Cherry-Pick #465)

---

dartsim/src/WorldFeatures_TEST.cc
test/Utils.hh
test/common_test/addexternalforcetorque.cc
test/common_test/link_features.cc
test/common_test/shape_features.cc
test/common_test/world_features.cc

Small housekeeping commit to reduce some duplicated code.

Refactor the VectorApprox to a single location

---

Changelog.md

Port `ign-physics2 ` ➡️  `ign-physics5`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/ign-physics5...ign-physics2

Merge ign-physics2 ➡️  ign-physics5

---

CMakeLists.txt
Changelog.md

Preparation for 5.3.1 release.
Comparison to 5.3.0: https://github.com/gazebosim/gz-physics/compare/ignition-physics5_5.3.0...ign-physics5
Needed by https://github.com/gazebosim/gz-sim/pull/1836

Prepare for 5.3.1 Release

---

Changelog.md
dartsim/src/SDFFeatures.cc

Port `ign-physics5 ` ➡️  `gz-physics6`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics6...ign-physics5

Merge ign-physics5 ➡️  gz-physics6

---

dartsim/src/SDFFeatures.cc

Port ign-physics2 to ign-physics5
Branch comparison: https://github.com/gazebosim/gz-physics/compare/ign-physics5...ign-physics2

Forward port 2 to 5

---

.github/ci-focal/before_cmake.sh
.github/ci/packages-focal.apt
.github/ci/packages.apt
.github/workflows/ci.yml
CMakeLists.txt
README.md
test/common_test/free_joint_features.cc
tutorials/06-physics-simulation-concepts.md

See https://github.com/gazebo-tooling/release-tools/issues/976

Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-physics7

---

.github/workflows/triage.yml
dartsim/src/Base.hh
dartsim/src/Base_TEST.cc
dartsim/src/CustomHeightmapShape.cc
dartsim/src/CustomHeightmapShape.hh
dartsim/src/EntityManagementFeatures.cc
dartsim/src/EntityManagementFeatures.hh
dartsim/src/FreeGroupFeatures.cc
dartsim/src/JointFeatures.cc
dartsim/src/JointFeatures.hh
dartsim/src/SDFFeatures.hh
dartsim/src/plugin.cc

Port `gz-physics6 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/main...gz-physics6

Merge gz-physics6 ➡️  main

---

CMakeLists.txt

Preparation for 7.0.0~pre2 release.
Comparison to 7.0.0~pre1: https://github.com/gazebosim/gz-physics/compare/gz-physics7_7.0.0-pre1...prep_7.0.0pre2
Needed by https://github.com/gazebosim/gz-sim/pull/2106

Prepare for 7.0.0~pre2 release

---

CMakeLists.txt
Changelog.md

Preparation for 5.3.2 release.
Comparison to 5.3.1: https://github.com/gazebosim/gz-physics/compare/ignition-physics5_5.3.1...ign-physics5
Needed by <PR(s)>

Prepare for 5.3.2 Release

---

dartsim/src/plugin.cc

Backport #529 to Fortress to fix #442 (gz-sim6 segfaults on macOS) on Fortress
See #529 and #442 for context.
Original commit message:
Unregister collision detectors when the darstim plugin is unloaded (#529)
Fixes a segfault that occurs due to destructors being removed from memory before they're called. ---------
**Use rebase-and-merge**
~~**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.~~

Fortress: backport fix for dartsim segfaults

---

CMakeLists.txt
Changelog.md

Preparation for 7.0.0 release.
Comparison to 7.0.0-pre4: https://github.com/gazebosim/gz-physics/compare/gz-physics7_7.0.0-pre4...gz-physics7
Needed by <PR(s)>

Prepare for 7.0.0 Release

---

.github/ci/packages.apt
CMakeLists.txt
examples/hello_world_loader/CMakeLists.txt
examples/hello_world_plugin/CMakeLists.txt
examples/simple_plugin/CMakeLists.txt
tutorials/06-physics-simulation-concepts.md

See https://github.com/gazebo-tooling/release-tools/issues/1027

Bumps in ionic : ci_matching_branch/bump_ionic_gz-physics8

---

bullet-featherstone/src/FreeGroupFeatures.cc
bullet-featherstone/src/JointFeatures.cc
bullet-featherstone/src/KinematicsFeatures.cc
bullet-featherstone/src/SDFFeatures.cc
test/common_test/CMakeLists.txt
test/common_test/detachable_joint.cc
test/common_test/simulation_features.cc
test/common_test/world_features.cc
test/common_test/worlds/detachable_joint.world
test/common_test/worlds/world_unsorted_links.sdf
tutorials/02_installation.md

Port `gz-physics6 ` ➡️  `gz-physics7`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics7...gz-physics6

Merge gz-physics6 ➡️  gz-physics7

---

.github/CODEOWNERS

Remove @mxgrey as code owner

---

.github/CODEOWNERS
dartsim/src/SDFFeatures.cc
test/common_test/world_features.cc
test/common_test/worlds/falling.world

Port ign-physics5 to gz-physics6
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics6...ign-physics5

Merge 5 -> 6

---

Changelog.md
bullet-featherstone/README.md
bullet-featherstone/src/Base.hh
bullet-featherstone/src/JointFeatures.cc
bullet-featherstone/src/JointFeatures.hh
bullet-featherstone/src/SDFFeatures.cc
bullet-featherstone/src/SDFFeatures.hh
bullet-featherstone/src/SimulationFeatures.cc
bullet-featherstone/src/SimulationFeatures.hh
test/common_test/CMakeLists.txt
test/common_test/joint_features.cc
test/common_test/worlds/test.world

Port `gz-physics7 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/main...gz-physics7

Merge gz-physics7 ➡️  main

---

CMakeLists.txt

Preparation for 8.0.0~pre2 release.
Comparison to 8.0.0pre1: https://github.com/gazebosim/gz-physics/compare/gz-physics8_8.0.0-pre1...prep_8.0.0pre2

Prepare for 8.0.0~pre2 release

---

tutorials/04-switching-physics-engines.md

Related with https://github.com/gazebosim/gazebo_test_cases/issues/1409

Fixed tutorial link

---

tutorials/05_plugin_loading.md

This PR updates the Dartsim version in the documentation to match the version used during testing (6.13.2). Please see https://github.com/gazebosim/gazebo_test_cases/issues/1415

Update Dartsim version to 6.13.2 in docs

---

bullet-featherstone/src/SimulationFeatures.cc
test/common_test/joint_features.cc

Backport #699 
**Note to maintainers**: Remember to **Rebase and Merge** with commit (not squash-merge or merge)

Backport bullet-featherstone joint velocity target reset 

---

Changelog.md

Addresses https://github.com/gazebosim/gz-physics/pull/703#discussion_r1834917349

Prepare for 7.4.0 Release (update changelog)

---

Changelog.md
bullet-featherstone/src/JointFeatures.cc
dartsim/src/GzCollisionDetector.cc
test/common_test/Worlds.hh
test/common_test/joint_features.cc
test/common_test/worlds/joint_offset_empty_links.sdf

Port gz-physics7 to gz-physics8
Branch comparison: https://github.com/gazebosim/gz-physics/compare/gz-physics8...gz-physics7

Merge gz-physics7 ➡️ gz-physics8

---

test/common_test/joint_features.cc

Cleans up test documentation
Removes an irrelevant reference from test documentation

Clean up comment in joint wrench test

---

bullet-featherstone/src/Base.cc
bullet-featherstone/src/Base.hh
bullet-featherstone/src/JointFeatures.cc
bullet-featherstone/src/SDFFeatures.cc
bullet-featherstone/src/SimulationFeatures.cc
dartsim/src/JointFeatures.cc
dartsim/src/JointFeatures.hh
dartsim/src/SDFFeatures_TEST.cc
include/gz/physics/Joint.hh
include/gz/physics/detail/Joint.hh
test/common_test/joint_features.cc
test/common_test/simulation_features.cc
test/common_test/worlds/test.world
tpe/plugin/src/SDFFeatures_TEST.cc

Port `gz-physics8 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-physics/compare/main...gz-physics8

Merge gz-physics8 ➡️  main

---

Changelog.md

Sorry @scpeters lost the review on https://github.com/gazebosim/gz-physics/pull/751.

Cleanup changelog for 8.2.0
